---
- name: "Install"
  ansible.builtin.include_tasks: "install.yaml"

- name: "Provide scripts"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0755"
  become: true
  loop:
    - {src: "restic-backup", dest: "/usr/bin/restic-backup"}

- name: If Arch
  when: ansible_distribution == "Archlinux"
  become: true
  block:

    - name: "Provide templates"
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      become: true
      loop:
        - {src: "restic-backup.service", dest: "/etc/systemd/system/restic-backup.service"}
        - {src: "restic-backup.timer", dest: "/etc/systemd/system/restic-backup.timer"}
      notify: Reload restic


- name: If Void
  when: ansible_distribution == "Void"
  become: true
  block:

    - name: Run backup every day in random time
      ansible.builtin.cron:
        name: "Run backup every day in random time"
        minute: "0"
        hour: "14"
        job: "/usr/bin/restic-backup backup-home"
        state: present
        user: "root"
