---
- name: "Install"
  ansible.builtin.include_tasks: "install.yaml"

- name: "Create dirs"
  ansible.builtin.file:
    dest: "{{ item.dir }}"
    state: directory
    mode: "0755"
  loop:
    - {dir: "{{ conf.folders.bin }}"}

- name: "Provide scripts"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ conf.folders.bin }}/{{ item.path }}"
    mode: "0755"
  with_community.general.filetree: '{{ role_path }}/templates/bin'
  when: item.state == 'file'
