config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_subversion: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_subversion_setup:
    src: subversion.sh
    dst: ~/.cache/setup/subversion.sh
    actions:
      - install_svn
  f_subversion:
    src: config
    dst: ~/.subversion/config
    actions:
      - install_svn
  f_subversion_bin_rm:
    src: svn-rm-rm
    dst: "{{@@ bin @@}}/svn-rm-rm"
    chmod: 0755
  f_subversion_bin_add:
    src: svn-add-add
    dst: "{{@@ bin @@}}/svn-add-add"
    chmod: 0755
actions:
  install_svn: "bash ~/.cache/setup/subversion.sh"
profiles:
  svn:
    dotfiles:
      - f_subversion_setup
      - f_subversion
      - f_subversion_bin_rm
      - f_subversion_bin_add
