config:
  import_variables:
    - "local_vars.yaml"
dotfiles:
  f_telegram_lock:
    src: telegram.lock
    dst: ~/.local/telegram.lock
    actions:
      - install_telegram
actions:
  pre:
    install_telegram: "{{@@ pm @@}} telegram-desktop"
profiles:
  telegram:
    dotfiles:
      - f_telegram_lock
