config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_telegram: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_telegram_lock:
    src: telegram.lock
    dst: ~/.local/telegram.lock
    actions:
      - install_telegram
  f_telegram_desktop:
    src: telegram.desktop
    dst: ~/.local/share/applications/favorites/telegram.desktop
actions:
  pre:
    install_telegram: "{{@@ pm @@}} telegram-desktop"
profiles:
  telegram:
    dotfiles:
      - f_telegram_lock
      - f_telegram_desktop
