config:
  import_variables:
    - "local_vars.yaml"
dotfiles:
  d_notes_config:
    src: user
    dst: ~/.config/systemd/user
    actions:
      - reload_notes
      - enable_notes_timer
      - start_notes_timer
      - start_notes_service
  f_notes_bin1:
    src: bin/add-note
    dst: "{{@@ bin @@}}/add-note"
    chmod: 0755
  f_notes_bin2:
    src: bin/jrnl
    dst: "{{@@ bin @@}}/jrnl"
    chmod: 0755
  f_notes_bin3:
    src: bin/notes-sync
    dst: "{{@@ bin @@}}/notes-sync"
    chmod: 0755
actions:
  post:
    reload_notes: "systemctl --user daemon-reload"
    enable_notes_timer: "systemctl --user enable notes-sync.timer"
    start_notes_service: "systemctl --user start notes-sync.service"
    start_notes_timer: "systemctl --user start notes-sync.timer"
profiles:
  notes:
    dotfiles:
      - d_notes_config
      - f_notes_bin1
      - f_notes_bin2
      - f_notes_bin3
