---
packages_archlinux:
  - extra/zip
  - community/vifm
  - extra/unzip
  - extra/p7zip
  - community/sshfs
  - community/curlftpfs
  - community/trash-cli
  - aur/archivemount-git
  - aur/epr-git

packages_void:
  - zip
  - vifm
  - unzip
  - p7zip
  - fuse-sshfs
  - curlftpfs
  - trash-cli
  - fuse-archivemount
# TODO: via src
# epr
