config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_rofi: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_rofi_lock:
    src: rofi.lock
    dst: ~/.local/rofi.lock
    actions:
      - install_rofi
  d_rofi_config:
    src: rofi
    dst: ~/.config/rofi
  f_rofi_bin_myip:
    src: bin/myip
    dst: "{{@@ bin @@}}/myip"
    chmod: 0755
  f_rofi_bin_calc:
    src: bin/rcalc
    dst: "{{@@ bin @@}}/rcalc"
    chmod: 0755
  f_rofi_bin_run:
    src: bin/rofi_run
    dst: "{{@@ bin @@}}/rofi_run"
    chmod: 0755
  f_rofi_bin_fav:
    src: bin/rofi-fav
    dst: "{{@@ bin @@}}/rofi-fav"
    chmod: 0755
  f_rofi_rcalc:
    src: rcalc.desktop
    dst: ~/.local/share/applications/favorites/rcalc.desktop
actions:
  pre:
    install_rofi: "{{@@ pm @@}} rofi rofi-calc"
profiles:
  rofi:
    dotfiles:
      - f_rofi_lock
      - d_rofi_config
      - f_rofi_bin_myip
      - f_rofi_bin_calc
      - f_rofi_bin_run
      - f_rofi_bin_fav
      - f_rofi_rcalc
