---
config:
  backup: true
  banner: false
  create: true
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
  dotpath: packages
  import_variables:
    - "local_vars.yaml"
  import_configs:
    - packages/aws/config.yaml
    - packages/bitwarden/config.yaml
    - packages/bluetooth/config.yaml
    - packages/browser/config.yaml
    - packages/containers/config.yaml
    - packages/cryptomator/config.yaml
    - packages/fonts/config.yaml
    - packages/gammastep/config.yaml
    - packages/i3/config.yaml
    - packages/mimeapps/config.yaml
    - packages/networkmanager/config.yaml
    - packages/notes/config.yaml
    - packages/obsidian/config.yaml
    - packages/pipewire/config.yaml
    - packages/rofi/config.yaml
    - packages/syncthing/config.yaml
    - packages/telegram/config.yaml
    - packages/terminal/config.yaml
    - packages/yubikey/config.yaml
dotfiles:
profiles:
  ewok-t14s:
    include:
      - aws
      - bitwarden
      - bluetooth
      - browser
      - containers
      - cryptomator
      - fonts
      - gammastep
      - i3
      - mimeapps
      - networkmanager
      - notes
      - obsidian
      - pipewire
      - rofi
      - syncthing
      - telegram
      - terminal
      - yubikey
    dynvariables:
      hostname: echo ewok-t14s
      _dotdrop_rootpath: dirname {{@@ _dotdrop_cfgpath @@}}
