---
config:
  backup: true
  banner: false
  create: true
  ignoreempty: false
  keepdot: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
  dotpath: packages
  import_variables:
    - "local_vars.yaml"
  import_configs:
    - packages/base/config.yaml
    - packages/direnv/config.yaml
    - packages/fish/config.yaml
    - packages/git/config.yaml
    - packages/kube/config.yaml
    - packages/lisps/config.yaml
    - packages/nix/config.yaml
    - packages/nvim/config.yaml
    - packages/scripts/config.yaml
    - packages/ssh/config.yaml
    - packages/starship/config.yaml
    - packages/svn/config.yaml
    - packages/terraform/config.yaml
    - packages/tmux/config.yaml
    - packages/vifm/config.yaml
dotfiles:
profiles:
  ewok-t14s:
    include:
      - base
      - direnv
      - fish
      - git
      - kube
      - lisps
      - nix
      - nvim
      - scripts
      - ssh
      - starship
      - svn
      - terraform
      - tmux
      - vifm
    dynvariables:
      hostname: echo ewok-t14s
      _dotdrop_rootpath: dirname {{@@ _dotdrop_cfgpath @@}}
  void:
    include:
      - base
    dynvariables:
      hostname: echo void
      _dotdrop_rootpath: dirname {{@@ _dotdrop_cfgpath @@}}
  ewok-rpi:
    include:
      - base
      - direnv
      - fish
      - git
      - kube
      - lisps
      - nix
      - nvim
    dynvariables:
      hostname: echo ewok-rpi
      _dotdrop_rootpath: dirname {{@@ _dotdrop_cfgpath @@}}
  vmi839551.contaboserver.net:
    include:
      - base
      - direnv
      - fish
      - git
      - kube
      - lisps
      - nix
      - nvim
    dynvariables:
      hostname: echo vmi839551.contaboserver.net
      _dotdrop_rootpath: dirname {{@@ _dotdrop_cfgpath @@}}
