- hosts: localhost

  roles:
    - base

  tasks:

    - name: Find all roles
      find:
        depth: 1
        file_type: directory
        paths: "{{ playbook_dir }}/roles"
      register: roles
      tags:
        - always

    - name: Use role in loop
      include_role:
        name: '{{ roleinputvar | basename }}'
      loop_control:
        loop_var: roleinputvar
      loop: "{{ roles.files | map(attribute='path') | list }}"
      tags:
        - always

  pre_tasks:

    - name: "Include local vars"
      tags:
        - always
      ignore_errors: True
      changed_when: False
      include_vars:
        file: ~/.vars.local

    - name: "Include default vars"
      tags:
        - always
      include_vars:
        file: "{{ playbook_dir }}/settings.yaml"
