---
- hosts: localhost

  pre_tasks:
    - name: "Include default vars"
      tags:
        - always
      include_vars:
        file: "{{ playbook_dir }}/local_vars.yaml"

    - name: "Profiles"
      tags:
        - always
      include_vars:
        file: "{{ playbook_dir }}/profiles.yaml"

  tasks:
    - name: "Use role in loop"
      include_role:
        name: "{{ roleinputvar }}"
      vars:
        conf: "{{ defaults|combine(machine[ansible_hostname].conf|default({})) }}"
      loop_control:
        loop_var: roleinputvar
      loop: "{{ roles | default(machine[ansible_hostname].roles) }}"
      tags:
        - always
