#!/usr/bin/bash

cd $(dirname "$0")

set -e

if [[ $# -eq 0 ]];then echo 'One toolbox name required("all" for all)'; exit 1;fi

function restart-tb()
{
    TB="$1"
    podman pull "nas:50000/$TB:latest"
    podman stop "$TB" || echo Seems stopped
    toolbox rm "$TB" || echo Seems Pod deleted
    toolbox create -i "nas:50000/$TB:latest" "$TB"
}

if [[ "$1" == "all" ]]; then
    restart-tb os
    restart-tb dev
    restart-tb gui
else
    restart-tb "$1"
fi
