config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_redshift: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_redshift_lock:
    src: redshift.lock
    dst: ~/.local/redshift.lock
    actions:
      - install_redshift
      - enable_redshift
      - start_redshift
  f_redshift_i3:
    src: i3_autostart
    dst: ~/.config/i3/autostart.d/redshift.conf
  f_redshift_reset_gamma:
    src: reset-gamma
    dst: "{{@@ bin @@}}/reset-gamma"
    chmod: 0755
actions:
  pre:
    install_redshift: "{{@@ yay @@}} geoclue redshift"
    enable_redshift: "systemctl --user enable  redshift-gtk"
    start_redshift: "systemctl --user start redshift-gtk"
profiles:
  redshift:
    dotfiles:
      - f_redshift_lock
      - f_redshift_i3
      - f_redshift_reset_gamma
