config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_direnv: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_direnv_setup:
    src: direnv.sh
    dst: ~/.cache/setup/direnv.sh
    actions:
      - install_direnv
  f_direnv_fish:
    src: 90_direnv_init.fish
    dst: ~/.config/fish/conf.d/90_direnv_init.fish
actions:
  install_direnv: "bash ~/.cache/setup/direnv.sh"
profiles:
  direnv:
    dotfiles:
      - f_direnv_setup
      - f_direnv_fish
