---
- name: "Install"
  ansible.builtin.include_tasks: "install.yaml"

- name: "Create dirs"
  ansible.builtin.file:
    dest: "{{ item.dir }}"
    state: directory
    mode: "0755"
  loop:
    - {dir: "{{ conf.folders.bin }}"}
    - {dir: "~/.config/systemd/user"}
    - {dir: "~/.config/sv"}

- name: Ensure bin directory structure exists
  ansible.builtin.file:
    path: "{{ conf.folders.bin }}/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: "{{ role_path }}/templates/bin"
  when: item.state == 'directory'

- name: Ensure scripts are populated from templates
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ conf.folders.bin }}/{{ item.path }}'
    mode: "0755"
  with_community.general.filetree: '{{ role_path }}/templates/bin'
  when: item.state == 'file'

- name: "If Archlinux"
  when: ansible_distribution == "Archlinux"
  block:
    - name: Ensure directory structure exists
      ansible.builtin.file:
        path: "~/.config/systemd/user/{{ item.path }}"
        state: directory
        mode: "0755"
      with_community.general.filetree: "{{ role_path }}/templates/systemd"
      when: item.state == 'directory'

    - name: Ensure configs are populated from templates
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '~/.config/systemd/user/{{ item.path }}'
        mode: "0644"
      with_community.general.filetree: '{{ role_path }}/templates/systemd'
      when: item.state == 'file'

- name: "If Void"
  when: ansible_distribution == "Void"
  block:

    - name: "Script cron-notes-sync"
      ansible.builtin.copy:
        content: |
          #!/bin/sh
          SSH_AUTH_SOCK={{ lookup('env', 'XDG_RUNTIME_DIR') }}/keyring/ssh
          SSH_ASKPASS=/usr/libexec/seahorse/ssh-askpass
          SSH_ASKPASS_REQUIRE=prefer
          {{ conf.folders.bin }}/notes-sync
        dest: "{{ lookup('env', 'HOME') }}/.config/sv/cron-notes-sync"
        mode: "0755"

    - name: "Service notes-sync"
      ansible.builtin.cron:
        name: "notes-sync"
        minute: "*/20"
        job: "{{ lookup('env', 'HOME') }}/.config/sv/cron-notes-sync"
