- import_tasks: cleanup.yaml

- name: "Install"
  tags:
    - video
  when: not work_machine is defined
  block:

    - name: "Install VLC"
      community.general.flatpak:
        name: org.videolan.VLC
        state: present
        executable: "~/.local/bin/flatpak-internal"
      tags:
        - vlc

    # https://github.com/lbryio/lbry-desktop/releases/download/v0.51.2/LBRY_0.51.2.AppImage

    - name: "Popcorntime Desktop entry"
      copy:
        content: |
          [Desktop Entry]
          Categories=Video
          Comment=Popcorntime
          Exec=toolbox run -c gui popcorntime
          Name=Popcorntime
          Terminal=false
          Type=Application
        dest: "~/.local/share/applications/popcorntime.desktop"
      tags:
        - popcorntime

    - name: "Lbry share dir"
      file:
        dest: "~/.local/share/lbry"
        state: directory

    - name: "Download Lbry AppImage"
      get_url:
        url: "https://github.com/lbryio/lbry-desktop/releases/download/v0.51.2/LBRY_0.51.2.AppImage"
        dest: "~/.local/share/lbry/lbry.AppImage"
        mode: 0755
        checksum: sha256:ed3cef0dcadb70759db8d7580f280b7b6775f2f9bc68ba34aacf75e4f245cd23

    - name: "Provide lbry execution script"
      copy:
        content: |
          #!/bin/bash
          ~/.local/share/lbry/lbry.AppImage "$@"
        dest: "~/.local/bin/lbry"
        mode: 0755

    - name: "Lbry Desktop Entry"
      copy:
        content: |
          [Desktop Entry]
          Categories=Utility
          Comment=LBRY Video Streaming
          Exec=lbry %U
          Name=Lbry
          Terminal=false
          Type=Application
        dest: "~/.local/share/applications/lbry.desktop"
