- name: "Cleanup"
  tags:
    - never
    - cleanup
  block:

    - name: "Stop service"
      ignore_errors: True
      systemd:
        daemon_reload: True
        scope: user
        enabled: False
        name: wallpaper
