- import_tasks: cleanup.yaml

- name: "Install"
  tags:
    - wallpaper
  block:

    - name: "Random wallpaper script"
      copy:
        content: |
          #!/bin/bash
          WALLPAPER="$(ls {{ directory.wallpapers }} | shuf -n 1)"
          swaymsg  output '*' bg "{{ directory.wallpapers }}/$WALLPAPER" fill
        dest: "~/.local/bin/random-wallpaper.sh"
        mode: 0755

    - name: "Systemd unit"
      copy:
        content: |
          [Unit]
          Description=Wallpaper
          BindsTo=sway-session.target

          [Service]
          Type=oneshot
          ExecStart={{ lookup('env', 'HOME') }}/.local/bin/random-wallpaper.sh

          [Install]
          WantedBy=sway-session.target
        dest: "~/.config/systemd/user/wallpaper.service"

    - name: "Wallpaper: Wallpaper enable service"
      ignore_errors: True
      systemd:
        daemon_reload: True
        scope: user
        enabled: True
        name: wallpaper
