config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_cryptomator: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_cryptomator_lock:
    src: cryptomator.lock
    dst: ~/.local/cryptomator.lock
    actions:
      - install_cryptomator
  f_cryptomator_config:
    src: settings.json
    dst: ~/.config/Cryptomator/settings.json
  f_cryptomator_i3:
    src: i3_autostart
    dst: ~/.config/i3/autostart.d/cryptomator.conf
actions:
  pre:
    install_cryptomator: "{{@@ yay @@}} cryptomator-bin"
profiles:
  cryptomator:
    dotfiles:
      - f_cryptomator_lock
      - f_cryptomator_config
      - f_cryptomator_i3
