config:
dynvariables:
  hash_starship: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_starship_setup:
    src: starship.sh
    dst: ~/.cache/setup/starship.sh
    actions:
      - install_starship
  f_starship_config:
    src: starship.toml
    dst: ~/.config/starship.toml
    actions:
      - install_starship
  f_starship_fish:
    src: 99_starship.fish
    dst: ~/.config/fish/conf.d/99_starship.fish
actions:
  install_starship: "bash ~/.cache/setup/starship.sh"
profiles:
  starship:
    dotfiles:
      - f_starship_setup
      - f_starship_config
      - f_starship_fish
