- import_tasks: cleanup.yaml

- name: "Install"
  tags:
    - vifm
  block:

    - name: Install base packages
      kewlfft.aur.aur:
        name: "{{ vifm_packages }}"
        use: yay
      become: yes
      become_user: aur_builder

    - name: "Provide config"
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: "vifm", dest: "~/.config" }

    - name: "Make scripts runnable"
      file:
        dest: "{{ item }}"
        mode: 0755
      with_fileglob:
        - "~/.config/vifm/scripts/*"

    - name: "Provide alias cd helper(fish)"
      tags:
        - fish
      copy:
        content: |
          function vifm
              set -l dst (command vifm --choose-dir - $argv)
              if test -z "$dst"
                  echo 'Directory picking cancelled/failed'
                  return 1
              end

              cd "$dst"
          end
        dest: "~/.config/fish/functions/vifm.fish"
