- import_tasks: cleanup.yaml

- name: "Install"
  tags:
    - gui
  block:

    - name: Install base packages
      kewlfft.aur.aur:
        name: "{{ gui_packages }}"
        use: yay
      become: yes
      become_user: aur_builder

    - name: "Provide config"
      ignore_errors: True
      copy:
        content: |
          {% set path = lookup('env', 'HOME') ~ "/.config/Zeal" %}
          [General]
          check_for_update=true
          hide_on_close=false
          minimize_to_systray=false
          show_systray_icon=true
          start_minimized=false

          [content]
          custom_css_file={{path}}/Zeal.css
          dark_mode=true
          default_fixed_font_size={{monospaceFontSize}}
          default_font_family=serif
          default_font_size={{regularFontSize}}
          disable_ad=true
          external_link_policy=@Variant(\0\0\0\x7f\0\0\0)Zeal::Core::Settings::ExternalLinkPolicy\0\0\0\0\0)
          fixed_font_family={{monospaceFont}}
          highlight_on_navigate=true
          minimum_font_size=0
          sans_serif_font_family=DejaVu Sans
          serif_font_family=DejaVu Serif
          smooth_scrolling=false

          [docsets]
          path={{path}}/docsets

          [global_shortcuts]
          show=

          [internal]
          install_id=10615a03-6af6-4b12-8712-0ec1429448a2
          version=0.6.1

          [proxy]
          authenticate=false
          host=
          password=
          port=0
          type=1
          username=

          [search]
          fuzzy_search_enabled=false

          [state]
          splitter_geometry=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x1\0\0\0\x4\xb0\0\xff\xff\xff\xff\x1\0\0\0\x1\0)
          toc_splitter_state=@ByteArray()

          [tabs]
          open_new_tab_after_active=false
        dest: "~/.config/Zeal/Zeal.conf"

    - name: "zeal.css"
      ignore_errors: True
      copy:
        content: |
          iframe {
              -webkit-filter: invert()
          }
          html {
              -webkit-filter: invert() hue-rotate(180deg) contrast(80%) brightness(120%) contrast(85%);
          }
          html img[src*=\"jpg\"], html img[src*=\"jpeg\"], html img[src*=\"jpg\"], html img[src*=\"jpeg\"] {
              -webkit-filter: brightness(100%) contrast(100%);
          }
        dest: "~/.config/Zeal/Zeal.css"
