#! /bin/sh
gap=10
PANEL_HEIGHT=27
export gap
export PANEL_HEIGHT

#This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $gap;
bspc config top_padding $(($PANEL_HEIGHT-$gap))
bspc config left_padding -$gap
bspc config right_padding -$gap
bspc config bottom_padding -$gap

#Various settings
bspc config gapless_monocle     false #Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config borderless_monocle  true
bspc config single_monocle true
# bspc config paddingless_monocle false
#bspc config ignore_ewmh_focus      true
#bspc config initial_polarity second_child
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
## Honor size hints: do not make windows smaller than they wish to be
#bspc config honor_size_hints true 

##Color settings
bspc config focused_border_color "#1ABB9B"
bspc config normal_border_color "#222D32"
#"#000000"
bspc config presel_feedback_color "#1ABB9B"
#"#8F3724"
bspc config border_width 1

bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true #Some keybindings automatically enable and disable this setting

#Settings for manual splitting
bspc config split_ratio         0.52

#bspc monitor -d i ii iii iv v vi vii viii ix x
#bspc monitor -d One Two Three Four Five Six Seven Eight Nine Ten
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d • • • • • • • • • •
#bspc monitor -d I II III IV V VI
bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc monitor -a 
bspc monitor -a 
bspc monitor -a 
bspc monitor -a 

###This creates and names desktops for multiple monitors.
# workspaces_multimonitor &

bspc rule -a "Blueman-manager" state=floating center=false
bspc rule -a Chromium private=on
bspc rule -a clipit state=floating center=true
bspc rule -a file-roller state=pseudo_tiled
bspc rule -a Firefox private=on
bspc rule -a gmrun state=floating center=true
bspc rule -a google-chrome-stable private=on
bspc rule -a google-chrome-unstable private=on
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a libreoffice state=tiled
bspc rule -a Pavucontrol state=floating center=true
bspc rule -a screenkey --unmanage
bspc rule -a Skype state=pseudo_tiled desktop=
bspc rule -a Slack desktop=
bspc rule -a "Syncthing GTK" state=floating center=false
bspc rule -a TelegramDesktop desktop=  follow=true
bspc rule -a wpa_gui state=pseudo_tiled
bspc rule -a Zathura state=pseudo_tiled
bspc rule -a "Google Play Music Desktop Player" desktop=

##  Autogap adjusts windowgap automatically according to the number of
##  windows on the desktop. Using it disables negative window gap.
#autogap &

##  This script balances all windows when new one is spawned 
# euclid_balancer &

##Edge-switcher switches to next workspace when moves moves to the 
##edge of the monitor (behavior similar to enlightenment)
#edge-switcher &

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
bspc config external_rules_command /usr/bin/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command /usr/bin/adjust-new-window

##Autostart apps
#Keybindings daemon
#sxhkd &

#Source autostartfile. Uncomment this if you use bspwm-git
. $HOME/.config/bspwm/autostart-user

# Alter compton settings if using intel graphics
GRAPHIC_CARD=$(lspci | grep -i "vga" | sed 's/.*://' | sed 's/(.*//' | sed 's/^[ \t]*//')

if [[ $(echo $GRAPHIC_CARD | grep -i 'intel\|lenovo') != "" ]]; then
    MCODE='initrd=\intel-ucode.img'
    sed -i 's/"xrender"/"glx"/' ~/.config/compton.conf
    grep -q 'vsync = "opengl-swc";' ~/.config/compton.conf || echo 'vsync = "opengl-swc";' >> ~/.config/compton.conf
fi

