config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_bitwarden: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_bitwarden_start:
    src: bitwarden.lock
    dst: ~/.local/bitwarden.lock
    actions:
      - install_bitwarden
  f_bitwarden_fish:
    src: 99_bw.fish
    dst: ~/.config/fish/conf.d/99_bw.fish
  f_bitwarden_bin:
    src: bw-reset
    dst: "{{@@ bin @@}}/bw-reset"
    chmod: 0755
  f_bitwarden_desktop:
    src: bitwarden.desktop
    dst: ~/.local/share/applications/favorites/bitwarden.desktop
actions:
  pre:
    install_bitwarden: "{{@@ pm @@}} community/bitwarden community/bitwarden-cli"
profiles:
  bitwarden:
    dotfiles:
      - f_bitwarden_start
      - f_bitwarden_fish
      - f_bitwarden_bin
      - f_bitwarden_desktop
