config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_kube: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_kube_lock:
    src: kube.lock
    dst: ~/.local/kube.lock
    actions:
      - install_kube
  f_kube_fish:
    src: 90-kube.fish
    dst: ~/.config/fish/conf.d/90-kube.fish
actions:
  pre:
    install_kube: "{{@@ pm @@}} kubectl kubectx minikube"
profiles:
  kube:
    dotfiles:
      - f_kube_lock
      - f_kube_fish
