config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_kube: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_kube_setup:
    src: kube.sh
    dst: ~/.cache/setup/kube.sh
    actions:
      - install_kube
  f_kube_fish:
    src: 90-kube.fish
    dst: ~/.config/fish/conf.d/90-kube.fish
actions:
  install_kube: "bash ~/.cache/setup/kube.sh"
profiles:
  kube:
    dotfiles:
      - f_kube_setup
      - f_kube_fish
