config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_tmux: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_tmux_setup:
    src: tmux.sh
    dst: ~/.cache/setup/tmux.sh
    actions:
      - install_tmux
  f_tmux:
    src: tmux.conf
    dst: ~/.config/tmux/tmux.conf
  f_tmux_bin_tm:
    src: tm
    dst: "{{@@ bin @@}}/tm"
    chmod: 0755
  f_tmux_bin_tssh:
    src: tssh
    dst: "{{@@ bin @@}}/tssh"
    chmod: 0755
actions:
  install_tmux: "bash ~/.cache/setup/tmux.sh"
profiles:
  tmux:
    dotfiles:
      - f_tmux_setup
      - f_tmux
      - f_tmux_bin_tm
      - f_tmux_bin_tssh
