#!/bin/bash
set -e
#
sudo mkdir -p /nix
sudo chown $USER /nix
mkdir -p ~/.nix-store
#
if ! mount | grep -q nix
then
  sudo mount -o bind ~/.nix-store /nix
fi
#
curl -L https://nixos.org/nix/install | sh -s -- --no-daemon
#
. /home/{{ conf.username }}/.nix-profile/etc/profile.d/nix.sh
#
nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
nix-channel --update
