config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_containers: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_containers_lock:
    src: containers.lock
    dst: ~/.local/containers.lock
    actions:
      - install_containers
      - install_containers_sub
actions:
  pre:
    install_containers: "{{@@ pm @@}} podman"
    install_containers_sub: "sudo usermod --add-subuids 100000-165535 --add-subgids 100000-165535 {{@@ user @@}}"
profiles:
  containers:
    dotfiles:
      - f_containers_lock
