config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_browser: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_browser_start:
    src: browser.lock
    dst: ~/.local/browser.lock
    actions:
      - install_browser
  f_browser_choose:
    src: choose-browser
    dst: "{{@@ bin @@}}/choose-browser"
    chmod: 0755
  f_browser_fish:
    src: 50_browser.fish
    dst: ~/.config/fish/conf.d/50_browser.fish
  f_browser_mime:
    src: org.custom.choose.browser.desktop
    dst: ~/.local/share/applications/org.custom.choose.browser.desktop
  f_browser_qute:
    src: qutebrowser.py
    dst: "~/.config/qutebrowser/config.py"
  f_browser_qute_wrapper:
    src: qutebrowser.sh
    dst: "{{@@ bin @@}}/qutebrowser"
    chmod: 0755
  f_browser_qute_choose:
    src: choose-qute
    dst: "{{@@ bin @@}}/choose-qute"
    chmod: 0755
  f_browser_qute_bitwarden:
    src: qute-bitwarden.py
    dst: "{{@@ bin @@}}/qute-bitwarden"
    chmod: 0755
  f_browser_qute_bw:
    src: qute-bw-login.sh
    dst: "{{@@ bin @@}}/qute-bw"
    chmod: 0755
actions:
  pre:
    install_browser: "{{@@ yay @@}} google-chrome qutebrowser python-adblock python-tldextract"
profiles:
  browser:
    dotfiles:
      - f_browser_start
      - f_browser_choose
      - f_browser_fish
      - f_browser_mime
      - f_browser_qute
      - f_browser_qute_wrapper
      - f_browser_qute_choose
      - f_browser_qute_bitwarden
      - f_browser_qute_bw
