---
packages_archlinux:
  - base-devel
  - btop
  - git
  - curl
  - zip
  - unzip
  - tar
  - xz
  - ncurses-base
  - ncurses-term
  - inetutils

packages_debian: []

packages_void:
  - btop
  - git
  - curl
  - xtools
  - socklog-void
  - cronie
  - zip
  - unzip
  - tar
  - xz
  - ncurses-base
  - ncurses-term
  - ntp
  - eudev

packages_remove_void:
  - python-pip
  - python-setuptools
  - python
