---
- name: "Import cleanup tasks"
  ansible.builtin.import_tasks: cleanup.yaml

- name: "Install"
  ansible.builtin.include_tasks: "install.yaml"

- name: "Create dirs"
  ansible.builtin.file:
    dest: "{{ item.dir }}"
    state: directory
    mode: "0755"
  loop:
    - {dir: "~/.config/gammastep"}
    - {dir: "~/.config/i3/autostart.d/"}

- name: "Provide configs"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - {src: "gammastep_config", dest: "~/.config/gammastep/config.ini"}
    - {src: "gammastep_i3_autostart", dest: "~/.config/i3/autostart.d/gammastep.conf"}
