- name: "Cleanup"
  become: True
  tags:
    - never
    - cleanup
  block:

    - name: "Stop services"
      ignore_errors: True
      systemd:
        name: "{{ item }}"
        enabled: False
        daemon_reload: True
        state: stopped
      loop:
          - "restic-backup.timer"
          - "restic-backup.service"

    - name: "Cleanup files"
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/usr/local/bin/restic-backup"
        - "/etc/systemd/system/restic-backup.service"
        - "/etc/systemd/system/restic-backup.timer"

- name: "Cleanup"
  become: True
  tags:
    - never
    - cleanup-hard
  block:

    - name: "Cleanup files"
      become: True
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/etc/restic_pass"
        - "/root/.config/rclone"
        - "/root/.cache/restic"
