- import_tasks: cleanup.yaml

- name: "Install"
  tags:
    - backup
  become: True
  block:

    - name: Install base packages
      kewlfft.aur.aur:
        name:
          - rclone
          - restic
        use: yay
        update_cache: True
      become: yes
      become_user: aur_builder

    - name: "Backup script"
      copy:
        content: |
          #!/bin/bash
          set -e

          PASS_FILE="/etc/restic_pass"

          RESTIC="restic -r {{ backup.repo }} -p $PASS_FILE"

          if [[ "$1" == "backup-home" ]]; then
            # Forget
            $RESTIC forget --keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 5 --prune

            # Backup
            $RESTIC backup \
              --exclude-caches \
              --exclude-if-present .nobackup \
              {% for path in backup.paths %}{{path}} {% endfor %}

          else
            $RESTIC "$@"
          fi
        dest: "/usr/local/bin/restic-backup"
        mode: 0755

    - name: "Systemd unit"
      copy:
        content: |
          [Service]
          CPUSchedulingPolicy=idle
          Environment=HOME=/root
          ExecStart=/usr/local/bin/restic-backup backup-home

          IOSchedulingClass=idle

          [Unit]
          Description=Restic backup
          Wants=network-online.target
          Requisite=ac.target
        dest: "/etc/systemd/system/restic-backup.service"
      notify:
        - "reload services"

    - name: "Systemd timer"
      copy:
        content: |
          [Install]
          WantedBy=timers.target
          WantedBy=ac.target

          [Timer]
          OnCalendar=daily
          Persistent=true
          Unit=restic-backup.service
          RandomizedDelaySec=3600

          [Unit]
          Description=Restic backup timer
          Requisite=ac.target
          PartOf=ac.target
        dest: "/etc/systemd/system/restic-backup.timer"
      notify:
        - "reload services"

    - name: "Start services"
      systemd:
        name: "restic-backup.timer"
        enabled: True
        daemon_reload: True
        state: started

    - name: "Start services"
      systemd:
        name: "restic-backup.service"
        enabled: True
        daemon_reload: True
