config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_base: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_base_start:
    src: base.lock
    dst: ~/.local/base.lock
    actions:
      - install_base
      - install_base_devel
  f_base_update:
    src: update-config
    dst: "{{@@ bin @@}}/update-config"
    chmod: 0755
  f_base_install:
    src: install-config
    dst: "{{@@ bin @@}}/install-config"
    chmod: 0755
  f_base_open:
    src: open
    dst: "{{@@ bin @@}}/open"
    chmod: 0755
actions:
  install_base: "mkdir -p ~/.cache/rpms ~/Pictures/Screenshots ~/mnt ~/share {{@@ bin @@}}"
  install_base_devel: "{{@@ yay @@}} base-devel community/btop"
profiles:
  base:
    dotfiles:
      - f_base_start
      - f_base_update
      - f_base_install
      - f_base_open
