config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_base: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_base_setup:
    src: base.sh
    dst: ~/.cache/setup/base.sh
    actions:
      - install_base
  f_base_update:
    src: update-config
    dst: "{{@@ bin @@}}/update-config"
    chmod: 0755
  f_base_install:
    src: install-config
    dst: "{{@@ bin @@}}/install-config"
    chmod: 0755
  f_base_open:
    src: open
    dst: "{{@@ bin @@}}/open"
    chmod: 0755
actions:
  install_base: "bash ~/.cache/setup/base.sh"
profiles:
  base:
    dotfiles:
      - f_base_setup
      - f_base_update
      - f_base_install
      - f_base_open
