config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_nvim: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_nvim_setup:
    src: nvim.sh
    dst: ~/.cache/setup/nvim.sh
    actions:
      - install_nvim
  f_nvim_config_init:
    src: neovim/init.lua
    dst: ~/.config/nvim/init.lua
  d_nvim_config_fnl:
    src: neovim/fnl
    dst: ~/.config/nvim/fnl
  f_nvim_fish:
    src: 20_nvim-vars.fish
    dst: ~/.config/fish/conf.d/20_nvim-vars.fish
  f_nvim_ctags:
    src: ctags
    dst: ~/.ctags
  f_nvim_vale:
    src: vale.ini
    dst: ~/.vale.ini
  f_nvim_bin:
    src: nvim
    dst: "{{@@ bin @@}}/vim"
    chmod: 0755
  f_nvim_bin_lazygit:
    src: lazygit
    dst: "{{@@ bin @@}}/gg"
    chmod: 0755
  f_nvim_clean_cache:
    src: nvim-clean-cache
    dst: "{{@@ bin @@}}/nvim-clean-cache"
    chmod: 0755
  f_nvim_cbfmt:
    src: cbfmt.toml
    dst: ~/.config/cbfmt.toml
actions:
  pre:
    cleanup_nvim_lua: "rm -rf ~/.config/nvim/lua"
    cleanup_nvim_fnl: "rm -rf ~/.config/nvim/fnl"
  install_nvim: "bash ~/.cache/setup/nvim.sh"
profiles:
  nvim:
    dotfiles:
      - f_nvim_setup
      - d_nvim_config_fnl
      - f_nvim_config_init
      - f_nvim_fish
      - f_nvim_ctags
      - f_nvim_vale
      - f_nvim_bin
      - f_nvim_bin_lazygit
      - f_nvim_clean_cache
      - f_nvim_cbfmt
