config:
  import_variables:
    - "local_vars.yaml"
dotfiles:
  f_nvim_lock:
    src: nvim.lock
    dst: ~/.local/nvim.lock
    actions:
      - install_nvim_nvim
      - install_nvim_coursier
      # - install_nvim_tools_apt
      - install_nvim_tools_arch
  f_nvim_config_init:
    src: neovim/init.lua
    dst: ~/.config/nvim/init.lua
    actions:
      - cleanup_nvim_lua
  d_nvim_config_fnl:
    src: neovim/fnl
    dst: ~/.config/nvim/fnl
    actions:
      - cleanup_nvim_lua
  f_nvim_fish:
    src: 20_nvim-vars.fish
    dst: ~/.config/fish/conf.d/20_nvim-vars.fish
  f_nvim_ctags:
    src: ctags
    dst: ~/.ctags
  f_nvim_vale:
    src: vale.ini
    dst: ~/.vale.ini
  f_nvim_bin:
    src: nvim
    dst: "{{@@ bin @@}}/vim"
    chmod: 0755
  f_nvim_bin_lazygit:
    src: lazygit
    dst: "{{@@ bin @@}}/gg"
    chmod: 0755
actions:
  pre:
    cleanup_nvim_lua: "rm -rf ~/.config/nvim/lua"
    cleanup_nvim_fnl: "rm -rf ~/.config/nvim/fnl"
    install_nvim_nvim: "{{@@ pm @@}} neovim lazygit"
    install_nvim_tools_arch: "if which yay;then {{@@ pm @@}} the_silver_searcher ripgrep python-pynvim tree-sitter npm gnu-netcat jq yq fzf;fi"
    install_nvim_tools_apt: "if which apt;then {{@@ pm @@}} silversearcher-ag python3-pynvim libtree-sitter-dev luarocks  ripgrep jq yq fzf;fi"
    install_nvim_coursier: "curl -o {{@@ bin @@}}/coursier https://git.io/coursier-cli"
profiles:
  nvim:
    dotfiles:
      - f_nvim_lock
      - d_nvim_config_fnl
      - f_nvim_config_init
      - f_nvim_fish
      - f_nvim_ctags
      - f_nvim_vale
      - f_nvim_bin
      - f_nvim_bin_lazygit
