config:
  # import_variables:
  #   - "local_vars.yaml"
dynvariables:
  hash_terraform: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_terraform_setup:
    src: terraform.sh
    dst: ~/.cache/setup/terraform.sh
    actions:
      - install_terraform
  f_terraform_fish:
    src: 90_tfenv_init.fish
    dst: ~/.config/fish/conf.d/90_tfenv_init.fish
  # f_terraform_bin:
  #   src: tfenv
  #   dst: "{{@@ bin @@}}/tfenv"
  #   chmod: 0755
actions:
  install_terraform: "bash ~/.cache/setup/terraform.sh"
profiles:
  terraform:
    dotfiles:
      - f_terraform_setup
      # - f_terraform_bin
      - f_terraform_fish
