- import_tasks: cleanup.yaml

- name: "Install"
  tags:
    - ssh
  block:

    - name: ".ssh dir"
      file:
        dest: "~/.ssh"
        state: directory
        mode: 0700

    - name: "Provide config"
      copy:
        content: |-
          {% for record in ssh %}
          Host "{{record.name}}"
          {% if record.hostname is defined %}
            HostName {{record.hostname}}
          {% endif %}
          {% if record.user is defined %}
            User {{record.user|default(lookup('env', 'USER'))}}
          {% endif %}
          {% if record.port is defined %}
            Port {{record.port|default(22)}}
          {% endif %}
          {% if record.identity_file is defined %}
            IdentityFile {{record.identity_file}}
          {% endif %}
          {% if record.proxy_command is defined %}
            ProxyCommand {{record.proxy_command}}
          {% endif %}
          {% if record.control_path is defined %}
            ControlPath {{record.control_path}}
          {% endif %}
          {% if record.control_master is defined %}
            ControlMaster {{record.control_master}}
          {% endif %}
          {% if record.extra is defined %}
            {{record.extra|indent(2)}}
          {% endif %}

          {% endfor %}
          Host *
            AddKeysToAgent yes
        dest: "~/.ssh/config"
