#!/usr/bin/env bash

STEP_SIZE=${STEP_SIZE:-5}

case $BLOCK_BUTTON in
  3) echo xset dpms force off ;; # right click
  4) brightnessctl s "$STEP_SIZE"+ > /dev/null ;; # scroll up
  5) brightnessctl s "$STEP_SIZE"- > /dev/null ;; # scroll down, decrease
esac

BRIGHTNESS=$(brightnessctl g)
echo "${BRIGHTNESS}"
