config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_PACKAGE: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_PACKAGE_setup:
    src: PACKAGE.sh
    dst: ~/.cache/setup/PACKAGE.sh
    actions:
      - install_PACKAGE
  d_PACKAGE:
    src: source
    dst: ~/.config/dest
    link: relative
  f_PACKAGE:
    src: source.file
    dst: ~/.config/dest.file
  f_PACKAGE_bin:
    src: source.file
    dst: "{{@@ bin @@}}/PACKAGE.sh"
    chmod: 0755
  f_PACKAGE_fish:
    src: source.file
    dst: ~/.config/fish/conf.d/00-PACKAGE.fish
actions:
  install_PACKAGE: "bash ~/.cache/PACKAGE.sh"
profiles:
  PACKAGE:
    dotfiles:
      - f_PACKAGE_setup
      - d_PACKAGE
      - f_PACKAGE
      - f_PACKAGE_bin
      - f_PACKAGE_fish
