config:
  dotpath: config
dynvariables:
  hash_vifm: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1
    -d' '"
dotfiles:
  f_vifm_setup:
    src: vifm.sh
    dst: ~/.cache/setup/vifm.sh
    actions:
      - install_vifm
  d_vifm:
    src: vifm
    dst: ~/.config/vifm
    cmpignore:
      - "vifm-help.txt"
      - "vifminfo.json"
    upignore:
      - "vifm-help.txt"
      - "vifminfo.json"
  f_vifm:
    src: vifm.fish
    dst: ~/.config/fish/functions/vifm.fish
actions:
  install_vifm: "bash ~/.cache/setup/vifm.sh"
profiles:
  vifm:
    dotfiles:
      - f_vifm_setup
      - d_vifm
      - f_vifm
