- import_tasks: cleanup.yaml

- name: "Install"
  tags:
    - flatpak

  block:

    - name: Setup flathub
      changed_when: False
      shell: |
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: "Config XDG_DATA"
      tags:
        - fish
      copy:
        content: |
          if command -vq flatpak
              # set -ga fish_user_paths ~/.local/share/flatpak/exports/bin /var/lib/flatpak/exports/bin
              fish_add_path -ga ~/.local/share/flatpak/exports/bin /var/lib/flatpak/exports/bin

              set -gxa --path XDG_DATA_DIRS ~/.local/share/flatpak/exports/share /usr/local/share /usr/share

              for install_dir in (flatpak --installations)
                  set -gxa XDG_DATA_DIRS $install_dir/exports/share
              end
          end
        dest: "~/.config/fish/conf.d/02_flatpak.fish"
