- 1.1.9
- _NAME: MX Keys Mini for Mac
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, onboard_profiles, report_rate, pointer_speed, dpi, speed-change, backlight-timed, reprogrammable-keys, persistent-remappable-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4100
  _modelId: B36A00000000
  _sensitive: {disable-keyboard-keys: false, divert-keys: true, fn-swap: true}
  _unitId: 34735FBA
  backlight: false
  change-host: null
  disable-keyboard-keys: {1: false}
  divert-keys: {226: 1, 227: 1, 229: 0, 231: 0, 232: 0, 233: 0, 259: 1, 264: 1, 266: 1, 284: 0, 285: 1}
  fn-swap: true
  multiplatform: 0
- _NAME: MX Anywhere 3
  _sensitive: {change-host: false, divert-keys: false, dpi: false, hires-scroll-mode: true, hires-smooth-invert: true, hires-smooth-resolution: true, reprogrammable-keys: false,
    smart-shift: false}
  _serial: E971B4F8
  _wpid: '4090'
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 196: 0}
  dpi: 1000
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 196: 196}
  smart-shift: 15
- _NAME: MX Anywhere 3
  _absent: [hi-res-scroll, lowres-scroll-mode, scroll-ratchet, thumb-scroll-invert, thumb-scroll-mode, onboard_profiles, report_rate, pointer_speed, speed-change,
    backlight, backlight-timed, fn-swap, persistent-remappable-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led,
    multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4100
  _modelId: B02540900000
  _sensitive: {change-host: false, dpi: true, hires-smooth-resolution: true, smart-shift: true}
  _unitId: E971B4F8
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 196: 0}
  dpi: 800
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 196: 196}
  smart-shift: 7
