config:
  import_variables:
    - "local_vars.yaml"
dotfiles:
  f_nix_fish:
    src: .config/fish/conf.d/10_nix-init.fish
    dst: ~/.config/fish/conf.d/10_nix-init.fish
  d_nix_nix:
    src: .config/nix
    dst: ~/.config/nix
  f_nix:
    src: nix-init
    dst: "{{@@ bin @@}}/nix-init"
    chmod: 0755
profiles:
  nix:
    dotfiles:
      - f_nix_fish
      - d_nix_nix
      - f_nix
