config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_vpn: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_vpn_lock:
    src: vpn.lock
    dst: ~/.local/vpn.lock
    actions:
      - install_vpn
      - reload_vpn
  f_vpn_vpn:
    src: vpn
    dst: /usr/bin/vpn
    chmod: 0755
  f_vpn_service:
    src: vpn.service
    dst: "/etc/systemd/system/vpn@.service"
    actions:
      - reload_vpn
actions:
  pre:
    install_vpn: "{{@@ pm @@}} openvpn"
    reload_vpn: "systemctl daemon-reload"
profiles:
  vpn:
    dotfiles:
      - f_vpn_lock
      - f_vpn_vpn
      - f_vpn_service
