config:
dotfiles:
  f_pipewire_start:
    src: pipewire.lock
    dst: ~/.local/pipewire.lock
    actions:
      - install_pipewire
      - install_pipewire1
      - install_pipewire2
actions:
  pre:
    install_pipewire: "{{@@ pm @@}} pipewire pipewire-pulse pipewire-alsa pipewire-jack pipewire-zeroconf pavucontrol alsa-utils"
    install_pipewire1: "{{@@ pm @@}} alsa-plugins alsa-lib alsa-firmware gstreamer gst-plugins-good gst-plugins-bad gst-plugins-base"
    install_pipewire2: "{{@@ pm @@}} gst-plugins-ugly volumeicon playerctl"
profiles:
  pipewire:
    dotfiles:
      - f_pipewire_start
