config:
dynvariables:
  hash_pipewire: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_pipewire_start:
    src: pipewire.lock
    dst: ~/.local/pipewire.lock
    actions:
      - install_pipewire
      - install_pipewire1
      - install_pipewire2
  f_pipewire_mixer:
    src: pulsemixer.desktop
    dst: ~/.local/share/applications/pulsemixer.desktop
  f_pipewire_mixer_fav:
    src: pulsemixer-fav.desktop
    dst: ~/.local/share/applications/favorites/pulsemixer.desktop
  f_pipewire_pkgbuild:
    src: pulsemixer.PKGBUILD
    dst: ~/.local/src/pulsemixer/PKGBUILD
    actions:
      - build_pipewire_pulsemixer
  f_piperwire_pulsemixer_config:
    src: pulsemixer.config
    dst: ~/.config/pulsemixer.cfg
    actions:
      - build_pipewire_pulsemixer
actions:
  pre:
    install_pipewire: "{{@@ yay @@}} pipewire pipewire-pulse pipewire-alsa pipewire-jack pipewire-zeroconf alsa-utils"
    install_pipewire1: "{{@@ yay @@}} alsa-plugins alsa-lib alsa-firmware gstreamer gst-plugins-good gst-plugins-bad gst-plugins-base"
    install_pipewire2: "{{@@ yay @@}} gst-plugins-ugly playerctl"
  post:
    build_pipewire_pulsemixer: "cd ~/.local/src/pulsemixer && makepkg -si --noconfirm"
profiles:
  pipewire:
    dotfiles:
      - f_pipewire_start
      - f_pipewire_mixer
      - f_pipewire_mixer_fav
      - f_pipewire_pkgbuild
      - f_piperwire_pulsemixer_config
