config:
dynvariables:
  hash_pipewire: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_pipewire_start:
    src: pipewire.lock
    dst: ~/.local/pipewire.lock
    actions:
      - install_pipewire
      - install_pipewire1
      - install_pipewire2
  f_pipewire_mixer:
    src: pulsemixer.desktop
    dst: ~/.local/share/applications/pulsemixer.desktop
  f_pipewire_mixer_fav:
    src: pulsemixer-fav.desktop
    dst: ~/.local/share/applications/favorites/pulsemixer.desktop
actions:
  pre:
    install_pipewire: "{{@@ pm @@}} pipewire pipewire-pulse pipewire-alsa pipewire-jack pipewire-zeroconf alsa-utils"
    install_pipewire1: "{{@@ pm @@}} alsa-plugins alsa-lib alsa-firmware gstreamer gst-plugins-good gst-plugins-bad gst-plugins-base"
    install_pipewire2: "{{@@ pm @@}} gst-plugins-ugly playerctl pulsemixer"
profiles:
  pipewire:
    dotfiles:
      - f_pipewire_start
      - f_pipewire_mixer
      - f_pipewire_mixer_fav
