config:
dynvariables:
  hash_lisps: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_lisps_setup:
    src: lisps.sh
    dst: ~/.cache/setup/lisps.sh
    actions:
      - install_lisps
actions:
  install_lisps: "bash ~/.cache/setup/lisps.sh"
profiles:
  lisps:
    dotfiles:
      - f_lisps_setup
