config:
dynvariables:
  hash_lisps: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_lisps_lock:
    src: lisps.lock
    dst: ~/.local/lisps.lock
    actions:
      - install_lisps
      - install_lisps_n
actions:
  pre:
    install_lisps: "{{@@ pm @@}} aur/babashka-bin community/clojure community/fennel"
    install_lisps_n: "if [[ \"{{@@ distro_id @@}}\" != \"manjaro-arm\" ]];then {{@@ pm @@}} aur/clj-kondo-bin; fi"
profiles:
  lisps:
    dotfiles:
      - f_lisps_lock
