config:
dynvariables:
  hash_lisps: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_lisps_lock:
    src: lisps.lock
    dst: ~/.local/lisps.lock
    actions:
      - install_lisps
actions:
  pre:
    install_lisps: "{{@@ pm @@}} aur/babashka-bin community/clojure community/fennel aur/clj-kondo-bin"
profiles:
  lisps:
    dotfiles:
      - f_lisps_lock
