config:
dotfiles:
  f_bluetooth_lock:
    src: bluetooth.lock
    dst: ~/.local/bluetooth.lock
    actions:
      - install_bluetooth
  f_bluetooth_i3:
    src: i3_autostart
    dst: ~/.config/i3/autostart.d/bluetooth.conf
actions:
  pre:
    install_bluetooth: "{{@@ pm @@}} blueberry blueman bluez bluez-libs bluez-utils"
profiles:
  bluetooth:
    dotfiles:
      - f_bluetooth_lock
      - f_bluetooth_i3
