config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_gammastep: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_gammastep_lock:
    src: gammastep.lock
    dst: ~/.local/gammastep.lock
    actions:
      - install_gammastep
  f_gammastep_config:
    src: config.ini
    dst: ~/.config/gammastep/config.ini
    actions:
      - restart_gammastep
  f_gammastep_i3:
    src: i3_autostart
    dst: ~/.config/i3/autostart.d/gammastep.conf
actions:
  pre:
    install_gammastep: "{{@@ yay @@}} gammastep geoclue"
    restart_gammastep: "systemctl --user restart gammastep-indicator"
profiles:
  gammastep:
    dotfiles:
      - f_gammastep_lock
      - f_gammastep_config
      - f_gammastep_i3
