FROM nas:50000/arch-base:12

ENV TB=dev

RUN curl -sfL https://direnv.net/install.sh | bash

USER yay

RUN yay -Syuu --noconfirm --needed

# Tools

RUN yay -S --needed --noconfirm \
  emacs-gcc-wayland-devel-bin

RUN yay -S --needed --noconfirm \
  tmux \
  starship htop \
  vifm trash-cli \
  unzip p7zip sshfs curlftpfs ts archivemount dpkg viu wl-clipboard \
  neovim \
  python-pynvim \
  netcat ctags \
  tree-sitter global \
  the_silver_searcher \
  lua53 hadolint-bin \
  languagetool luacheck \
  shellcheck tflint \
  vale yamllint helm \
  rust-analyzer terraform-ls \
  lua-language-server bash-language-server \
  dockerfile-language-server nodejs-livedown \
  pyright vscode-json-languageserver python-lsp-server \
  yaml-language-server \
  gopls fzf ripgrep \
  aws-cli-v2-bin \
  rnix-lsp \
  svn \
  git \
  git-crypt git-trim pass-git-helper \
  rclone \
  restic \
  lastpass-cli \
  viddy \
  dfc exa bat fd \
  epr \
  whois \
  jq \
  clj-kondo-bin clojure-lsp-bin babashka \
  pandoc cmake ttf-ancient-fonts

USER root

RUN mkdir /nix && chown 1000 /nix

COPY locale.conf /etc/locale.conf
RUN locale-gen
