- import_tasks: cleanup.yaml

- name: "Install"
  tags:
    - emacs
  block:

    - name: Install base packages
      kewlfft.aur.aur:
        name: "{{ emacs_packages }}"
        use: yay
      become: yes
      become_user: aur_builder

    - name: "Ensure config dir exists"
      file:
        dest: "{{ item }}"
        state: directory
      loop:
        - "~/.config/emacs"
        - "~/.cache/emacs/backups"
        - "~/.cache/emacs/auto-save"

    - name: "Ensure config dir exists"
      file:
        dest: "{{ item }}"
        state: absent
      loop:
        - "~/.emacs.d"

    - name: "EnvVars"
      tags:
        - fish
      copy:
        content: |
          set -gx EDITOR "em";
          set -gx VISUAL "em";
          set -gx GUI_EDITOR "em";
        dest: "~/.config/fish/conf.d/20_emacs-vars.fish"

    - name: "Command"
      copy:
        content: |
          #!/bin/fish
          /usr/bin/emacsclient -a "/usr/bin/emacs" $argv
        dest: "~/.local/bin/{{ item }}"
        mode: 0755
      loop:
        - "em"

    - name: "vterm helper"
      copy:
        content: |
          function vterm_printf;
              if begin; [  -n "$TMUX" ]  ; and  string match -q -r "screen|tmux" "$TERM"; end
                  # tell tmux to pass the escape sequences through
                  printf "\ePtmux;\e\e]%s\007\e\\" "$argv"
              else if string match -q -- "screen*" "$TERM"
                  # GNU screen (screen, screen-256color, screen-256color-bce)
                  printf "\eP\e]%s\007\e\\" "$argv"
              else
                  printf "\e]%s\e\\" "$argv"
              end
          end
        dest: "~/.config/fish/conf.d/01_vterm_helper.fish"
        mode: 0755

    - name: Provide config
      changed_when: False
      shell: |
        /usr/bin/emacs --batch --eval "(require 'org)" --eval '(org-babel-tangle-file "{{ role_path }}/templates/emacs/emacs.org")'

    - name: "Enable emacs-daemon"
      ignore_errors: True
      systemd:
        daemon_reload: True
        scope: user
        enabled: True
        name: emacs
