- name: "Cleanup"
  tags:
    - never
    - cleanup
  block:

    - name: "Stop daemon"
      ignore_errors: True
      systemd:
        scope: user
        name: rslsync
        daemon_reload: True
        enabled: False
        state: stopped

    - name: "Cleanup files"
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "~/.config/rslsync"
