- name: "Cleanup"
  tags:
    - never
    - cleanup
  block:

    - name: "Cleanup files"
      become: True
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/home/{{username}}/.librewolf/profile.default/extensions"
        - "/home/{{username}}/.librewolf/profile.default/chrome"
        - "/home/{{username}}/.local/share/librewolf/"

- name: "Cleanup"
  tags:
    - never
    - cleanup-hard
  block:

    - name: "Cleanup files"
      become: True
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/home/{{username}}/.librewolf"
