- import_tasks: cleanup.yaml

- import_tasks: librewolf.yaml
- import_tasks: firefox.yaml

- name: "Install"
  tags:
    - browser
  block:

#    - name: Install base packages
#      kewlfft.aur.aur:
#        name: librewolf-bin
#        use: yay
#      become: yes
#      become_user: aur_builder

    - name: "choose-browser"
      copy:
        content: |
          #!/bin/env bash
          $(echo "firefox|google-chrome-stable" | rofi_run -dmenu -i -l 20 -p "Open url in:" -sep "|") "$1"
        dest: "~/.local/bin/choose-browser"
        mode: 0755

    - name: "EnvVars"
      tags:
        - fish
      copy:
        content: |
          set -gx BROWSER "choose-browser";
        dest: "~/.config/fish/conf.d/browser-vars.fish"

    - name: "Desktop Entry for ChooseBrowser"
      copy:
        content: |
          [Desktop Entry]
          Categories=Network;WebBrowser
          Comment=Choose browser to open URL
          Exec=choose-browser %U
          Name=ChooseBrowser
          Terminal=false
          Type=Application
        dest: "~/.local/share/applications/org.custom.choose.browser.desktop"
