---
- name: "Install"
  ansible.builtin.include_tasks: "install.yaml"

- name: "Install firefox"
  ansible.builtin.include_tasks: "firefox.yaml"

- name: "Install vieb"
  ansible.builtin.include_tasks: "vieb.yaml"

- name: "Install qutebrowser"
  ansible.builtin.include_tasks: "qutebrowser.yaml"

- name: "Create dirs"
  ansible.builtin.file:
    dest: "{{ item.dir }}"
    state: directory
    mode: "0755"
  loop:
    - {dir: "{{ conf.folders.bin }}"}
    - {dir: "~/.config/fish/conf.d"}
    - {dir: "~/.config/bash/profile.d"}
    - {dir: "~/.local/share/applications/"}
    - {dir: "~/Downloads"}
    - {dir: "~/.local/share/appimages/"}
    - {dir: "~/.vieb/"}

- name: "Provide configs"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - {src: "config/50_browser.sh", dest: "~/.config/bash/profile.d/50_browser.sh"}
    - {src: "config/org.custom.choose.browser.desktop", dest: "~/.local/share/applications/org.custom.choose.browser.desktop"}

- name: Ensure bin directory structure exists
  ansible.builtin.file:
    path: "{{ conf.folders.bin }}/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: "{{ role_path }}/templates/bin"
  when: item.state == 'directory'

- name: Ensure scripts are populated from templates
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ conf.folders.bin }}/{{ item.path }}'
    mode: "0755"
  with_community.general.filetree: '{{ role_path }}/templates/bin'
  when: item.state == 'file'
