- name: "Create dirs"
  ansible.builtin.file:
    dest: "{{ item.dir }}"
    state: directory
    mode: "0755"
  loop:
    - {dir: "{{ conf.folders.bin }}"}
    - {dir: "~/.local/share/appimages/"}
    - {dir: "~/.local/share/icons/hicolor"}
    - {dir: "~/.vieb/"}

- name: "Provide configs"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - {src: "config/vieb-work.desktop", dest: "~/.local/share/applications/vieb-work.desktop"}
    - {src: "config/vieb.desktop", dest: "~/.local/share/applications/vieb.desktop"}
    - {src: "config/viebrc", dest: "~/.vieb/viebrc"}

- name: "Download VieB"
  ansible.builtin.get_url:
    url: "https://github.com/Jelmerro/Vieb/releases/download/9.7.0/Vieb-9.7.0.AppImage"
    dest: "~/.local/share/appimages/vieb.AppImage"
    mode: "0755"
    checksum: "sha256: d784ae6b3779993bdd6e70b65bbd3ee3c6a7269786b188af91dd8afb9656e968"

- name: Provide icons
  ansible.builtin.file:
    dest: "~/.local/share/icons/hicolor/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: "{{ role_path }}/files/hicolor"
  when: item.state == 'directory'

- name: Provide icons
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '~/.local/share/icons/hicolor/{{ item.path }}'
    mode: "0644"
  with_community.general.filetree: '{{ role_path }}/files/hicolor'
  when: item.state == 'file'

- name: Ensure bin directory structure exists
  ansible.builtin.file:
    path: "{{ conf.folders.bin }}/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: "{{ role_path }}/templates/bin_vieb"
  when: item.state == 'directory'

- name: Ensure scripts are populated from templates
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ conf.folders.bin }}/{{ item.path }}'
    mode: "0755"
  with_community.general.filetree: '{{ role_path }}/templates/bin_vieb'
  when: item.state == 'file'
