---
- name: "Install"
  ansible.builtin.include_tasks: "install.yaml"

- name: "Add subuids and subgids"
  ansible.builtin.command: "usermod --add-subuids 100000-165535 --add-subgids 100000-165535 {{ conf.username }}"
  become: true

- name: "Add user to a docker group"
  become: true
  ansible.builtin.user:
    name: "{{ conf.username }}"
    groups: docker
    append: true

- name: "If Archlinux"
  when: ansible_distribution == "Archlinux"
  block:

    - name: "Enable docker"
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true
      become: true
