- import_tasks: cleanup.yaml

- name: "Install"
  tags:
    - cryptomator
  block:

    - name: "Share dir"
      file:
        dest: "~/.local/share/Cryptomator"
        state: directory

    - name: "Download Cryptomator AppImage"
      get_url:
        url: "https://github.com/cryptomator/cryptomator/releases/download/1.6.3/cryptomator-1.6.3-x86_64.AppImage"
        dest: "~/.local/share/Cryptomator/cryptomator-bin"
        mode: 0755
        checksum: sha256:b1780d804d9edbfaf604a9432fd20f526563afb526548648a313c8f50e2fc784

    - name: "Provide execution script"
      copy:
        content: |
          #!/bin/bash
          ~/.local/share/Cryptomator/cryptomator-bin "$@"
        dest: "~/.local/bin/cryptomator"
        mode: 0755

    - name: "Desktop Entry"
      copy:
        content: |
          [Desktop Entry]
          Categories=Utility
          Comment=Cryptomator
          Exec=cryptomator %U
          Name=Cryptomator
          Terminal=false
          Type=Application
        dest: "~/.local/share/applications/cryptomator.desktop"
