- name: "reload services"
  become: True
  systemd:
    name: "{{ item }}"
    enabled: False
    daemon_reload: True
  loop:
    - "tlp"
    - "ac_init"
    - "bat_init"

- name: "reload services"
  become: True
  systemd:
    name: "{{ item }}"
    enabled: True
    daemon_reload: True
  loop:
    - "tlp"
    - "ac_init"
    - "bat_init"

- name: "reload udev"
  become: True
  shell: udevadm control --reload-rules
