---
- name: "Install"
  ansible.builtin.include_tasks: "install.yaml"

- name: "Create dirs"
  ansible.builtin.file:
    dest: "{{ item.dir }}"
    state: directory
    mode: "0755"
  loop:
    - {dir: "{{ conf.folders.bin }}"}
    - {dir: "~/.config/fish/conf.d"}
    - {dir: "~/.local/src/tgenv"}
    - {dir: "~/.terraform.d/plugin-cache"}

- name: "Provide configs"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - {src: "90_tfenv_init.fish", dest: "~/.config/fish/conf.d/90_tfenv_init.fish"}
    - {src: "tgenv.PKGBUILD", dest: "~/.local/src/tgenv/PKGBUILD"}
    - {src: "tgenv.install", dest: "~/.local/src/tgenv/tgenv.install"}
  notify: "Install tgenv"

# - name: "Provide scripts"
#   ansible.builtin.template:
#     src: "{{ item.src }}"
#     dest: "{{ conf.folders.bin }}/{{ item.dest | default(item.src) }}"
#     mode: "0755"
#   loop:
#     - {src: "tfenv", dest: ""}

- name: If Arch
  when: ansible_distribution == "Archlinux"
  become: true
  block:
    - name: "Add user to a tfenv group"
      become: true
      ansible.builtin.user:
        name: "{{ conf.username }}"
        groups: "{{ item }}"
        append: true
      loop:
        - tfenv
        - tgenv
