- import_tasks: cleanup.yaml

- name: "Install"
  tags:
    - email
    - mail
  block:

    - name: "Share dir"
      file:
        dest: "~/.local/share/zoho"
        state: directory

    - name: "Download Lbry AppImage"
      get_url:
        url: "https://downloads.zohocdn.com/zmail-desktop/linux/zoho-mail-desktop-x64-v1.3.2.AppImage"
        dest: "~/.local/share/zoho/zoho.AppImage"
        mode: 0755
        checksum: sha256:d57b105779c2e33e6df5426bdcab05ec0db8e311adbbcd0f2bb38c982d11fcca

    - name: "execution script"
      copy:
        content: |
          #!/bin/bash
          ~/.local/share/zoho/zoho.AppImage "$@"
        dest: "~/.local/bin/zoho"
        mode: 0755

    - name: "Desktop Entry"
      copy:
        content: |
          [Desktop Entry]
          Categories=Office
          Comment=ZohoMail
          Exec=zoho %U
          Name=Zoho
          Terminal=false
          Type=Application
        dest: "~/.local/share/applications/zoho.desktop"
