---
- name: "Install"
  ansible.builtin.include_tasks: "install.yaml"

- name: "Create dirs"
  ansible.builtin.file:
    dest: "{{ item.dir }}"
    state: directory
    mode: "0755"
  loop:
    - {dir: "{{ conf.folders.bin }}"}
    - {dir: "~/.config/rofi"}

- name: "Provide configs"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - {src: "rcalc.desktop", dest: "~/.local/share/applications/favorites/rcalc.desktop"}

- name: Ensure bin directory structure exists
  ansible.builtin.file:
    path: "{{ conf.folders.bin }}/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: "{{ role_path }}/templates/bin"
  when: item.state == 'directory'

- name: Ensure scripts are populated from templates
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ conf.folders.bin }}/{{ item.path }}'
    mode: "0755"
  with_community.general.filetree: '{{ role_path }}/templates/bin'
  when: item.state == 'file'

- name: Ensure directory structure exists
  ansible.builtin.file:
    path: "~/.config/rofi/{{ item.path }}"
    state: directory
    mode: "0755"
  with_community.general.filetree: "{{ role_path }}/templates/rofi"
  when: item.state == 'directory'

- name: Ensure configs are populated from templates
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '~/.config/rofi/{{ item.path }}'
    mode: "0644"
  with_community.general.filetree: '{{ role_path }}/templates/rofi'
  when: item.state == 'file'
