- import_tasks: cleanup.yaml

- name: "Install"
  tags:
    - rofi
  block:

    - name: Install base packages
      kewlfft.aur.aur:
        name:
          - rofi
          - rofi-calc
        use: yay
      become: yes
      become_user: aur_builder

    - name: "Provide config dir"
      file:
        dest: "~/.config/rofi"
        state: directory

    - name: "Rofi theme colors"
      copy:
        content: |
          * {
            background: #{{colors.color10}}ff;
            foreground: #{{colors.foreground}}ff;
            lightbg:    #{{colors.color11}}ff;
            lightfg:    #{{colors.foreground}}ff;
            red:        #{{colors.color1}}ff;
            blue:       #{{colors.color4}}ff;
            font:       "{{ regularFont }} {{ regularFontSize }}";
          }
        dest: "~/.config/rofi/colors.rasi"

    - name: "Rofi theme"
      template:
        src: "{{ item }}"
        dest: "~/.config/rofi/{{ item | basename }}"
      loop: "{{ lookup('fileglob', '{{ role_path }}/templates/*.rasi', wantlist=True) }}"

    - name: "dmcalc"
      copy:
        content: |
          rofi -show calc -modi calc -no-show-match -no-sort
        dest: "~/.local/bin/rofi-calc"
        mode: 0755

    - name: "dmmyip"
      copy:
        content: |
          dmenucmd="rofi_run -dmenu -p MyIP: $@"
          while : ; do
              result=$(curl ifconfig.me | $dmenucmd)
              if [[ $result ]]; then
                  printf "$result" | wl-copy
              fi
              [[ $result ]] || break
          done
        dest: "~/.local/bin/myip"
        mode: 0755

    - name: "rofi_run"
      copy:
        content: |
          #!/bin/env fish
          /usr/bin/rofi \
           -icon-theme "Papirus" -show-icons -terminal lxterminal -theme default $argv
        dest: "~/.local/bin/rofi_run"
        mode: 0755
