config:
  import_variables:
    - "local_vars.yaml"
dotfiles:
  f_aws_lock:
    src: aws.lock
    dst: ~/.local/aws.lock
    actions:
      - install_aws
actions:
  pre:
    install_aws: "{{@@ pm @@}} community/aws-cli-v2 community/eksctl"
profiles:
  aws:
    dotfiles:
      - f_aws_lock
