config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_aws: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_aws_lock:
    src: aws.lock
    dst: ~/.local/aws.lock
    actions:
      - install_aws
actions:
  pre:
    install_aws: "{{@@ pm @@}} community/aws-cli-v2 community/eksctl"
profiles:
  aws:
    dotfiles:
      - f_aws_lock
