---
- name: "Install"
  ansible.builtin.include_tasks: "install.yaml"

- name: "Create dirs"
  ansible.builtin.file:
    dest: "{{ item.dir }}"
    state: directory
    mode: "0755"
  loop:
    - {dir: "{{ conf.folders.bin }}"}
    - {dir: "~/.config/tmux"}

- name: "Provide configs"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - {src: "tmux.conf", dest: "~/.config/tmux/tmux.conf"}

- name: "Provide scripts"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ conf.folders.bin }}/{{ item.dest | default(item.src) }}"
    mode: "0755"
  loop:
    - {src: "tm", dest: ""}
    - {src: "tssh", dest: ""}
