- import_tasks: cleanup.yaml

- name: "Install"
  tags:
    - tmux
  block:

    - name: Install base packages
      kewlfft.aur.aur:
        name:
          - tmux
        use: yay
      become: yes
      become_user: aur_builder

    - name: "Provide config dir"
      file:
        dest: "~/.config/tmux"
        state: directory

    - name: "Provide config"
      template:
        src: "tmux.conf"
        dest: "~/.config/tmux/tmux.conf"

    - name: "tm"
      copy:
        content: |
          #!/bin/env bash
          if [[ $1 == "" ]];then
            SESSION="main"
          else
            SESSION="$1"
          fi
          tmux attach -t $SESSION || tmux new -s $SESSION
        dest: "~/.local/bin/tm"
        mode: 0755

    - name: "tssh"
      copy:
        content: |
          #!/bin/env bash
          argv=( "$@" )
          C=1
          tmux new-window "ssh ''${argv[0]}"
          for i in "''${argv[@]:1}";do
          tmux split-window -h "ssh $i"
          C=$((C + 1))
          done
          if [ "$#" -gt 4 ];then
          tmux select-layout tiled
          else
          tmux select-layout even-vertical
          fi
        dest: "~/.local/bin/tssh"
        mode: 0755
