- name: "Cleanup"
  tags:
    - never
    - cleanup
  block:

    - name: "Cleanup files"
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "~/.config/lxterminal"
        - "~/.config/alacritty"
        - "~/.config/starship.toml"
