config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_sudoers: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_sudoers_lock:
    src: sudoers.lock
    dst: ~/.local/sudoers.lock
    actions:
      - install_sudoers
  d_sudoers_etc_sudoers:
    src: etc/sudoers.d
    dst: /etc/sudoers.d
actions:
  pre:
    install_sudoers: "{{@@ pm @@}} sudo"
profiles:
  sudoers:
    dotfiles:
      - d_sudoers_etc_sudoers
