FROM nas:50000/arch-base:12

ENV TB=gui

ENV GTK_THEME=Adwaita:dark

RUN sudo -u yay yay -S --noconfirm --needed popcorntime-bin
RUN sudo -u yay yay -S --noconfirm --needed 1password
RUN sudo -u yay yay -S --noconfirm --needed rslsync
RUN sudo -u yay yay -S --noconfirm --needed notion-app

COPY ./flatpak /usr/bin/flatpak

RUN chmod +x /usr/bin/flatpak

CMD /bin/bash
