- import_tasks: cleanup.yaml

- name: "Install"
  tags:
    - edu
  block:

    - name: "Install Anki"
      community.general.flatpak:
        name: net.ankiweb.Anki
        state: present
        executable: "~/.local/bin/flatpak-internal"

    - name: "Install Foliate"
      community.general.flatpak:
        name: com.github.johnfactotum.Foliate
        state: present
        executable: "~/.local/bin/flatpak-internal"

    - name: "Install Dialekt"
      community.general.flatpak:
        name: com.github.gi_lom.dialect
        state: present
        executable: "~/.local/bin/flatpak-internal"

    - name: "Install GoldenDict"
      community.general.flatpak:
        name: org.goldendict.GoldenDict
        state: present
        executable: "~/.local/bin/flatpak-internal"

    - name: "Patch GoldenDict run script"
      copy:
        content: |
          #!/bin/sh
          exec /usr/bin/flatpak run --branch=stable --arch=x86_64 --persist=dicts org.goldendict.GoldenDict "$@"
        dest: "~/.local/bin/org.goldendict.GoldenDict"
        mode: 0755
