AUDIO_ENABLE     = no
BACKLIGHT_ENABLE = no
BLUETOOTH_ENABLE = no
BOOTMAGIC_ENABLE = no
COMMAND_ENABLE   = yes
CONSOLE_ENABLE   = no
DYNAMIC_MACRO_ENABLE = yes
EXTRAKEY_ENABLE  = yes
LEADER_ENABLE = no
MIDI_ENABLE      = no
MOUSEKEY_ENABLE  = yes
NKRO_ENABLE      = yes
RGBLIGHT_ENABLE  = no
TAP_DANCE_ENABLE = no
UNICODE_ENABLE   = no

EXTRAFLAGS += -flto
