config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_git: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_git_setup:
    src: git.sh
    dst: ~/.cache/setup/git.sh
    actions:
      - install_git
  d_git:
    src: git
    dst: ~/.config/git
  f_git_fish:
    src: 90_git-aliases.fish
    dst: ~/.config/fish/conf.d/90_git-aliases.fish
  f_git_bin:
    src: sign
    dst: "{{@@ bin @@}}/sign"
    chmod: 0755
actions:
  install_git: "bash ~/.cache/setup/git.sh"
profiles:
  git:
    dotfiles:
      - f_git_setup
      - d_git
      - f_git_fish
      - f_git_bin
