---
- name: "Import cleanup tasks"
  ansible.builtin.import_tasks: cleanup.yaml

- name: "Install"
  ansible.builtin.include_tasks: "install.yaml"

- name: "Create dirs"
  ansible.builtin.file:
    dest: "{{ item.dir }}"
    state: directory
    mode: "0755"
  loop:
    - {dir: "~/.local/share/applications/favorites"}

- name: "Provide configs"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - {src: "telegram.desktop", dest: "~/.local/share/applications/favorites/telegram.desktop"}
    - {src: "skype.desktop", dest: "~/.local/share/applications/favorites/skype.desktop"}

- name: "If Void"
  when: ansible_os_family == "Void"
  block:

    - name: "Install via flatpak"
      community.general.flatpak:
        name: "{{ item }}"
      loop:
        - "com.skype.Client"
