---

- name: "Install packages Arch"
  kewlfft.aur.aur:
    name: "{{ packages_archlinux }}"
    use: yay
  become: true
  become_user: aur_builder
  when: packages_archlinux|default([])|length > 0 and ansible_distribution == "Archlinux"

- name: "Remove packages Arch"
  ansible.builtin.pacman:
    name: "{{ packages_remove_archlinux }}"
    state: absent
  become: true
  when: packages_remove_archlinux|default([])|length > 0 and ansible_distribution == "Archlinux"

- name: "Install packages Debian"
  ansible.builtin.apt:
    name: "{{ packages_debian }}"
    state: present
    update_cache: false
  become: true
  when: packages_debian|default([])|length > 0 and ansible_distribution == "Debian"

- name: "Remove packages Debian"
  ansible.builtin.apt:
    name: "{{ packages_debian }}"
    state: absent
    update_cache: false
  become: true
  when: packages_remove_debian|default([])|length > 0 and ansible_distribution == "Debian"

- name: "Install packages Void"
  community.general.xbps:
    name: "{{ packages_void }}"
    state: present
    update_cache: false
  become: true
  when: packages_void|default([])|length > 0 and ansible_distribution == "Void"

- name: "Remove packages Void"
  community.general.xbps:
    name: "{{ packages_void }}"
    state: absent
    update_cache: false
  become: true
  when: packages_remove_void|default([])|length > 0 and ansible_distribution == "Void"
