---
- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    validate: 'visudo -cf %s'

- name: "Install packages"
  kewlfft.aur.aur:
    name: "{{ packages_archlinux }}"
    use: yay
  become: true
  become_user: aur_builder

- name: "Configure locales"
  ansible.builtin.copy:
    dest: /etc/locale.gen
    content: |
      en_US.UTF-8 UTF-8
      ru_RU.UTF-8 UTF-8
      ky_KG.UTF-8 UTF-8
    mode: "0644"
  notify: "Reconfigure locales"
  become: true

