- name: "Cleanup"
  tags:
    - never
    - cleanup
  block:

    - name: "Cleanup dirs"
      tags:
        - cleanup-config
      file:
        dest: "{{ item.dir }}"
        state: absent
      loop:
        - { dir: "~/.cache/rpms" }
        - { dir: "~/.config/systemd/" }
        - { dir: "~/.local/bin" }
        - { dir: "~/.local/share/applications" }

- name: "Cleanup"
  tags:
    - never
    - cleanup-hard
  block:

    - name: "Cleanup podman"
      ignore_errors: True
      shell: |
        podman system prune -f

    - name: "Cleanup dirs"
      become: True
      file:
        dest: "{{ item.dir }}"
        state: absent
      loop:
        - { dir: "/home/{{ username }}/.cache" }
        - { dir: "/home/{{ username }}/.local" }
        - { dir: "/home/{{ username }}/.config" }
        - { dir: "/home/{{ username }}/.var" }
        - { dir: "/home/{{ username }}/.sync" }
        - { dir: "/home/{{ username }}/.ssh" }
