---
# Archlinux
- name: "Install"
  ansible.builtin.include_tasks: "arch.yaml"
  when: ansible_distribution == "Archlinux"

# Debian
- name: "Install"
  ansible.builtin.include_tasks: "debian.yaml"
  when: ansible_distribution == "Debian"

# VoidLinux
- name: "Install"
  ansible.builtin.include_tasks: "void.yaml"
  when: ansible_distribution == "Void"

- name: "Create dirs"
  ansible.builtin.file:
    dest: "{{ item.dir }}"
    state: directory
    mode: "0755"
  loop:
    - {dir: "{{ conf.folders.bin }}"}
    - {dir: "~/mnt"}
    - {dir: "~/share"}
    - {dir: "~/Documents"}
    - {dir: "~/Downloads"}
    - {dir: "~/tmp"}
    - {dir: "~/.config/bash/profile.d"}
    - {dir: "~/.config/bash/rc.d"}

- name: "Provide scripts"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0755"
  loop:
    - {src: "install-config", dest: "{{ conf.folders.bin }}/install-config"}
    - {src: "open", dest: "{{ conf.folders.bin }}/open"}

- name: "Provide configs"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - {src: "profile", dest: "~/.bash_profile"}
    - {src: "profile", dest: "~/.profile"}
    - {src: "bashrc", dest: "~/.bashrc"}
    - {src: "10-base.sh", dest: "~/.config/bash/rc.d/10-base.sh"}
    - {src: "10-base.sh", dest: "~/.config/bash/profile.d/10-base.sh"}

- name: "Provide configs"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  become: true
  when: ansible_distribution != "MacOSX"
  loop:
    - {src: "10-sudoers", dest: "/etc/sudoers.d/10-sudoers"}
