- import_tasks: cleanup.yaml

- name: Upgrade
  kewlfft.aur.aur:
    use: yay
    update_cache: True
    upgrade: True
  become: yes
  become_user: aur_builder
  tags:
    - never
    - upgrade

- name: "Install"
  tags:
    - always
  block:

    - name: "Create basic dirs"
      file:
        dest: "{{ item.dir }}"
        state: directory
      loop:
        - { dir: "~/.cache/rpms" }
        - { dir: "~/.config/fish/conf.d" }
        - { dir: "~/.config/fish/functions" }
        - { dir: "~/.config/systemd/" }
        - { dir: "~/.config/systemd/user" }
        - { dir: "~/.local/bin" }
        - { dir: "~/.local/share/applications" }
        - { dir: "~/Pictures" }
        - { dir: "~/Pictures/Screenshots" }
        - { dir: "~/mnt" }
        - { dir: "~/share" }

    - name: "aliases"
      copy:
        content: |
          #!/bin/bash
          {{item.cmd}}
        dest: "~/.local/bin/{{item.alias}}"
        mode: 0755
      loop:
        - {alias: "rebuild-os", cmd: 'bash {{playbook_dir}}/rebuild.sh "$@"'}
        - {alias: "rebuild-check", cmd: 'bash {{playbook_dir}}/rebuild.sh -C "$@"'}

    - name: Create the `aur_builder` user
      become: yes
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel

    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        validate: 'visudo -cf %s'

    - name: Install base packages
      kewlfft.aur.aur:
        name: "{{ base_packages }}"
        use: yay
        update_cache: True
      become: yes
      become_user: aur_builder
