---

- blockinfile:
    path: /etc/pacman.conf
    block: |
      [chaotic-aur]
      Server = http://lonewolf-builder.duckdns.org/$repo/x86_64
      Server = http://chaotic.bangl.de/$repo/x86_64
      Server = https://repo.kitsuna.net/x86_64
  become: True

- pacman_key:
    id: 3056513887B78AEB
    keyserver: keys.mozilla.org
    state: present
  become: True

- pacman:
    update_cache: yes
    upgrade: yes
  become: True

- pacman:
    name:
        - vim
        - nautilus
        - insync-nautilus
        - python-nautilus
        - tracker-miners
        - tracker
        - upower
        - podman
    state: absent
  become: True

- pacman:
    name:
      - base-devel
      - gcc
      - rclone
      - sshuttle
    state: present
  become: True

- aur:
    name: "{{ item }}"
    skip_installed: True
  loop: [
      "tmux", "python2", "python3",
      "python-virtualenv", "unzip", "p7zip",
      "zsh-autosuggestions", "restic", "trash-cli",
      "nvme-cli", "par", "sshfs", "curlftpfs", "archivemount",
      "rbenv", "ruby-build", "moc", "jq", "pyenv",
      "pyenv-virtualenv", "npm", "blacklist_pcspkr",
      "gotty", "docker", "vifm", "python-ueberzug",
      "unzip", "fzf", "reptyr", "cabextract", "dfc",
      "gnu-netcat"
      ]

- file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: True
  loop:
    - { src: "{{ role_path }}/files/.tmux.conf", dest: "~/.tmux.conf" }
    - { src: "{{ role_path }}/files/.zshrc", dest: "~/.zshrc" }
    - { src: "{{ role_path }}/files/.zsh", dest: "~/.zsh" }
    - { src: "{{ role_path }}/files/.zprofile", dest: "~/.zprofile" }
    - { src: "{{ role_path }}/files/.profile", dest: "~/.profile" }
    - { src: "{{ role_path }}/files/vifm", dest: "~/.vifm" }
    - { src: "{{ role_path }}/files/vifm", dest: "~/.config/vifm" }

- git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  loop:
      - { repo: "https://github.com/tmux-plugins/tmux-resurrect", dest: "~/.tmux/resurrect" }
      - { repo: "git://github.com/robbyrussell/oh-my-zsh.git", dest: "~/.oh-my-zsh" }

- file:
    path: "~/.local/bin"
    state: directory

- get_url:
    url: "https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage"
    dest: "~/.local/bin/appimagetool"
    mode: 0755

- lineinfile:
    path: /etc/systemd/logind.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  become: True
  notify: logind-restart
  loop:
    - { regexp: "^HandlePowerKey=", line: "HandlePowerKey=ignore" }
    - { regexp: "HandleSuspendKey=", line: "HandleSuspendKey=suspend" }
    - { regexp: "HandleHibernateKey=", line: "HandleHibernateKey=ignore" }
    - { regexp: "HandleLidSwitch=", line: "HandleLidSwitch=suspend" }
    - { regexp: "HandleLidSwitchExternalPower=", line: "HandleLidSwitchExternalPower=ignore" }
    - { regexp: "HandleLidSwitchDocked=", line: "HandleLidSwitchDocked=ignore" }

- name: adding existing user "{{ ansible_user }}" to some groups
  user:
     name: "{{ ansible_user }}"
     groups: wheel,docker,rfkill
     append: yes
  become: True
