config:
  import_variables:
    - "local_vars.yaml"
dynvariables:
  hash_i3: "sha1sum $(dirname {{@@ _dotdrop_dotpath @@}})/config.yaml | cut -f1 -d' '"
dotfiles:
  f_i3_lock:
    src: i3.lock
    dst: ~/.local/i3.lock
    actions:
      - install_i3
      - install_i3_1
      - install_i3_2
      - install_i3_3
      - install_i3_4
      - install_i3_5
      - install_i3_fm
      - install_i3_fm1
  f_i3_config:
    src: config
    dst: ~/.config/i3/config
  f_i3_pcmanfm:
    src: pcmanfm.conf
    dst: ~/.config/pcmanfm/default/pcmanfm.conf
  f_i3_status:
    src: i3status-config.toml
    dst: ~/.config/i3status-rust/config-default.toml
  f_i3_xcape:
    src: xcape.service
    dst: ~/.config/systemd/user/xcape.service
    actions:
      - enable_i3_xcape
      - start_i3_xcape
  f_i3_nitrogen:
    src: nitrogen.cfg
    dst: ~/.config/nitrogen/nitrogen.cfg
  f_i3_parcellite:
    src: parcelliterc
    dst: ~/.config/parcellite/parcelliterc
  d_i3_bin:
    src: bin
    dst: "{{@@ bin @@}}"
    chmod: 0755
    ignore_missing_in_dotdrop: true
  f_i3_bin_xdo:
    src: bin/xdotool-mod
    dst: "{{@@ bin @@}}/xdotool-mod"
    chmod: 0755
  f_i3_gtk2:
    src: gtk2.ini
    dst: ~/.gtkrc-2.0
  f_i3_gtk3:
    src: gtk3.ini
    dst: ~/.config/gtk-3.0/settings.ini
  f_i3_xresources:
    src: xresources
    dst: ~/.Xresources
  f_i3_autorandr:
    src: autorandr
    dst: ~/.config/autorandr/settings.ini
actions:
  pre:
    install_i3: "{{@@ pm @@}} adapta-gtk-theme autotiling caffeine-ng flameshot i3blocks dunst"
    install_i3_1: "{{@@ pm @@}} i3status-rust i3-wm light nitrogen papirus-icon-theme xcape"
    install_i3_2: "{{@@ pm @@}} xdotool xkb-switch-i3 xorg-server xorg-apps xorg-xinit"
    install_i3_3: "{{@@ pm @@}} solaar xautolock xss-lock betterlockscreen autorandr"
    install_i3_4: "{{@@ pm @@}} pcmanfm viewnior xclip aur/dracula-gtk-theme"
    install_i3_5: "{{@@ pm @@}} zathura zathura-pdf-mupdf zathura-djvu zathura-cb"
    install_i3_fm: "{{@@ pm @@}} gvfs gvfs-afc gvfs-gphoto2 gvfs-mtp gvfs-nfs gvfs-smb mtpfs udiskie"
    install_i3_fm1: "{{@@ pm @@}} udisks2 xdg-user-dirs parcellite"
  post:
    enable_i3_xcape: "systemctl --user enable xcape"
    start_i3_xcape: "systemctl --user start xcape"
profiles:
  i3:
    dotfiles:
      - f_i3_lock
      - f_i3_config
      - f_i3_status
      - d_i3_bin
      - f_i3_bin_xdo
      - f_i3_nitrogen
      - f_i3_pcmanfm
      - f_i3_xcape
      - f_i3_parcellite
      - f_i3_gtk2
      - f_i3_gtk3
      - f_i3_xresources
      - f_i3_autorandr
