- import_tasks: cleanup.yaml

- name: "Install"
  tags:
    - power
    - powersave
  become: True
  block:

    - name: Install base packages
      pacman:
        name: power-profiles-daemon
        state: absent

    - name: Install base packages
      kewlfft.aur.aur:
        name: tlp
        use: yay
        update_cache: True
      become: yes
      become_user: aur_builder

    - name: "Create dirs"
      file:
        dest: "{{ item }}"
        state: directory
      loop:
        - /etc/systemd/logind.conf.d/
        - /etc/systemd/sleep.conf.d/

    - name: "TLP config"
      ignore_errors: True
      copy:
        content: |
          CPU_BOOST_ON_AC=1
          CPU_BOOST_ON_BAT=0
          USB_BLACKLIST_BTUSB=1
          START_CHARGE_THRESH_BAT0=75
          STOP_CHARGE_THRESH_BAT0=95
          START_CHARGE_THRESH_BAT1=75
          STOP_CHARGE_THRESH_BAT1=95
          RESTORE_THRESHOLDS_ON_BAT=1
        dest: "/etc/tlp.conf"
      notify: "reload services"

    - name: "Systemd target battery"
      become: "{{ item.become }}"
      copy:
        content: |
          [Unit]
          Description=On battery power
          DefaultDependencies=no
          # StopWhenUnneeded=yes
        dest: "{{ item.dest }}"
      loop:
        - dest: "/etc/systemd/system/battery.target"
          become: True
        - dest: "{{ lookup('env', 'HOME') }}/.config/systemd/user/battery.target"
          become: False
      notify: "reload services"

    - name: "Systemd target ac"
      become: "{{ item.become }}"
      copy:
        content: |
          [Unit]
          Description=On AC power
          DefaultDependencies=no
          # StopWhenUnneeded=yes
        dest: "{{ item.dest }}"
      loop:
        - dest: "/etc/systemd/system/ac.target"
          become: True
        - dest: "{{ lookup('env', 'HOME') }}/.config/systemd/user/ac.target"
          become: False
      notify: "reload services"

    - name: "Init AC targets"
      copy:
        content: |
          [Unit]
          Description=Init AC target
          After=multi-user.target tlp.service
          Before=shutdown.target

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/run-on-ac /usr/local/bin/ac_bat_target ac_start

          [Install]
          WantedBy=multi-user.target
        dest: "/etc/systemd/system/ac_init.service"
      notify: "reload services"

    - name: "Init Battery targets"
      copy:
        content: |
          [Unit]
          Description=Init Battery target
          After=multi-user.target tlp.service
          Before=shutdown.target

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/run-on-bat /usr/local/bin/ac_bat_target bat_start

          [Install]
          WantedBy=multi-user.target
        dest: "/etc/systemd/system/bat_init.service"
      notify: "reload services"

    - name: "Start/Stop battery/ac"
      copy:
        content: |
          #!/usr/bin/env bash

          case "$1" in
            ac_start)
              /usr/bin/systemctl start ac.target
              sudo -u {{ username }} /usr/bin/systemctl --user start ac.target
              ;;
            ac_stop)
              /usr/bin/systemctl stop ac.target
              sudo -u {{ username }} /usr/bin/systemctl --user stop ac.target
              ;;
            bat_start)
              /usr/bin/systemctl start battery.target
              sudo -u {{ username }} /usr/bin/systemctl --user start battery.target
              ;;
            bat_stop)
              /usr/bin/systemctl stop battery.target
              sudo -u {{ username }} /usr/bin/systemctl --user stop battery.target
              ;;
            *)
              echo "No command"
              exit 2
          esac

        dest: "/usr/local/bin/ac_bat_target"
        mode: 0755

    - name: "enable targets"
      become: True
      systemd:
        name: "{{ item }}"
        enabled: True
        daemon_reload: True
      loop:
        - "ac_init"
        - "bat_init"

    - name: "start tlp"
      become: True
      systemd:
        name: "tlp"
        enabled: True
        daemon_reload: True
        state: started

    - name: "Udev rule"
      copy:
        content: |
          SUBSYSTEM=="power_supply", KERNEL=="AC", ATTR{online}=="0", RUN+="/usr/local/bin/ac_bat_target bat_start"
          SUBSYSTEM=="power_supply", KERNEL=="AC", ATTR{online}=="0", RUN+="/usr/local/bin/ac_bat_target ac_stop"
          SUBSYSTEM=="power_supply", KERNEL=="AC", ATTR{online}=="1", RUN+="/usr/local/bin/ac_bat_target ac_start"
          SUBSYSTEM=="power_supply", KERNEL=="AC", ATTR{online}=="1", RUN+="/usr/local/bin/ac_bat_target bat_stop"

          SUBSYSTEM=="power_supply", KERNEL=="ADP1", ATTR{online}=="0", RUN+="/usr/local/bin/ac_bat_target bat_start"
          SUBSYSTEM=="power_supply", KERNEL=="ADP1", ATTR{online}=="0", RUN+="/usr/local/bin/ac_bat_target ac_stop"
          SUBSYSTEM=="power_supply", KERNEL=="ADP1", ATTR{online}=="1", RUN+="/usr/local/bin/ac_bat_target ac_start"
          SUBSYSTEM=="power_supply", KERNEL=="ADP1", ATTR{online}=="1", RUN+="/usr/local/bin/ac_bat_target bat_stop"
        dest: "/etc/udev/rules.d/99-powertargets.rules"
      notify: reload udev

    # - name: "Enable tlp se"
    #   shell:
    #     chdir: "/etc/selinux_custom"
    #     creates: "/etc/selinux_custom/enable-tlp.pp"
    #     cmd: |
    #       echo 'type=AVC msg=audit(1637598556.058:2592): avc:  denied  { getattr } for  pid=47741 comm="tlp" path="/usr/bin/systemctl" dev="dm-0" ino=285150 scontext=system_u:system_r:tlp_t:s0-s0:c0.c1023 tcontext=system_u:object_r:systemd_systemctl_exec_t:s0 tclass=file permissive=0' | audit2allow -M enable-tlp
    #       semodule -X 300 -i enable-tlp.pp

    - name: "Configure logind"
      copy:
        content: |
          [Login]
          HandlePowerKey=ignore
          HandleSuspendKey={{ suspend_type | default("suspend-then-hibernate") }}
          #HandleHibernateKey=hibernate
          HandleLidSwitch={{ suspend_type | default("suspend-then-hibernate") }}
          HandleLidSwitchExternalPower=ignore
          HandleLidSwitchDocked=ignore
          HandleRebootKey=reboot
        dest: "/etc/systemd/logind.conf.d/laptop.conf"

    - name: "Configure sleepd"
      copy:
        content: |
          [Sleep]
          AllowSuspend=yes
          SuspendMode=
          SuspendState=mem standby
          AllowHibernation=yes
          HibernateMode=platform shutdown
          HibernateState=disk
          AllowSuspendThenHibernate=yes
          HibernateDelaySec=240min
        dest: "/etc/systemd/sleep.conf.d/laptop.conf"
