---

- lineinfile:
    path: /etc/X11/xorg.conf.d/00-keyboard.conf
    regexp: '^.*Option "XkbLayout" .*'
    line: '        Option "XkbLayout" "us,ru"'
  become: True

- pacman:
    name:
        - palemoon-bin
        - xfce4-power-manager
        - xst
    state: absent
  become: True

- pacman:
    name: [
        "termite", "siji-git", "ttf-unifont", "nerd-fonts-noto-sans-mono",
        "xclip", "xsel", "autorandr", "timeshift", "ttf-liberation",
        "xorg-xbacklight", "manjaro-pulse", "pa-applet", "pavucontrol", "pulseaudio-bluetooth",
        "blueman", "zathura", "zathura-cb", "zathura-djvu", "zathura-pdf-mupdf",
        "flameshot", "todoist-linux-bin", "slack-desktop", "redshift-gtk-git", "zeal",
        "masterpdfeditor-free", "firefox", "albert", "muparser","inotify-tools",
        "xdotool", "xorg-xwininfo", "uget", "calibre-python3", "deluge", "fbreader",
        "syncthing-gtk", "discord"
        ]
    state: present
  become: True

- aur:
    name: [
        "cawbird", "cryptomator", "ldoce5viewer-pyqt5-git", "grive-git", 
         "enpass-bin", "gpmdp" 
        ]
    skip_installed: True

- file:
    path: "{{ item }}"
    mode: '0755'
    state: directory
  loop:
    -  "~/.local/share/albert/org.albert.extension.python/modules/"
    -  "~/.config/albert"

- file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: True
  loop:
    - { src: "{{ role_path }}/files/termite", dest: "~/.config/termite" }
    - { src: "{{ role_path }}/files/.i3", dest: "~/.i3" }
    - { src: "{{ role_path }}/files/.i3status.conf", dest: "~/.i3status.conf" }
    - { src: "{{ role_path }}/files/.xprofile", dest: "~/.xprofile" }
    - { src: "{{ role_path }}/files/.Xresources", dest: "~/.Xresources" }
    - { src: "{{ role_path }}/files/Zeal", dest: "~/.config/Zeal" }
    - { src: "{{ role_path }}/files/albert/modules/locate.py", dest: "~/.local/share/albert/org.albert.extension.python/modules/locate.py" }
    - { src: "{{ role_path }}/files/albert/albert.conf", dest: "~/.config/albert/albert.conf" }

# Not implemented yet
#  if [ -d $HOME/.puppetlsp ]; then rm -rf $HOME/.puppetlsp;fi
#  git clone --depth 1 https://github.com/lingua-pupuli/puppet-editor-services.git $HOME/.puppetlsp
#  cd $HOME/.puppetlsp
#  eval "$(rbenv init -)"
#  rbenv install 2.5.7
#  rbenv shell 2.5.7
#  gem install puppet puppet-lint r10k
#  bundle install
