---
- name: "Install"
  ansible.builtin.include_tasks: "install.yaml"

- name: "Create dirs"
  ansible.builtin.file:
    dest: "{{ item.dir }}"
    state: directory
    mode: "0755"
  loop:
    - {dir: "~/.config/i3/autostart.d/"}
    - {dir: "~/.config/syncthing-gtk/"}

- name: "Provide configs"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - {src: "syncthing-gtk", dest: "~/.config/syncthing-gtk/config.json"}
    - {src: "i3_autostart", dest: "~/.config/i3/autostart.d/syncthing-gtk.conf"}

- name: If Arch
  when: ansible_distribution == "Archlinux"
  become: true
  block:

    - name: Enable service
      ansible.builtin.service:
        name: syncthing@ataranchiev
        state: stopped
        enabled: false

- name: If Void
  when: ansible_distribution == "Void"
  become: true
  block:

    - name: "Create dirs"
      ansible.builtin.file:
        dest: "{{ item.dir }}"
        state: directory
        mode: "0755"
      loop:
        - {dir: "/etc/sv/syncthing-{{ conf.username }}"}

    - name: Ensure service is populated from templates
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '/etc/sv/syncthing-{{ conf.username }}/{{ item.path }}'
        mode: "0755"
      with_community.general.filetree: '{{ role_path }}/templates/service'
      when: item.state == 'file'

    - name: Ensure trigger is populated from templates
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '/etc/run_on.ac/syncthing-{{ conf.username }}.{{ item.path }}'
        mode: "0755"
      with_community.general.filetree: '{{ role_path }}/templates/trigger'
      when: item.state == 'file'

    - name: Enable service
      ansible.builtin.command: ln -s /etc/sv/syncthing-{{ conf.username }} /var/service/
      args:
        creates: /var/service/syncthing-{{ conf.username }}
