---
- name: "Import cleanup tasks"
  ansible.builtin.import_tasks: cleanup.yaml

- name: "Install"
  ansible.builtin.include_tasks: "install.yaml"

- name: "Create dirs"
  ansible.builtin.file:
    dest: "{{ item.dir }}"
    state: directory
    mode: "0755"
  loop:
    - {dir: "~/.config/i3/autostart.d/"}
    - {dir: "~/.config/syncthing-gtk/"}

- name: "Provide configs"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - {src: "syncthing-gtk", dest: "~/.config/syncthing-gtk/config.json"}
    - {src: "i3_autostart", dest: "~/.config/i3/autostart.d/syncthing-gtk.conf"}
