#!/usr/bin/env bash

set -e

cd $(dirname "$0")

if [[ "$1" == "-r" ]]; then
    shift

    # roles are comma separated
    roles="$1"

    shift
    # roles are comma separated
    for role in $(echo "$roles" | tr ',' ' '); do
        ansible-playbook -D {{playbook_dir}}/main.yaml -e "roles=['${role}']" "$@"
    done
    # ansible-playbook -D {{playbook_dir}}/main.yaml -e "roles=['${role}']" "$@"
    exit 0
fi

ansible-playbook -D {{playbook_dir}}/main.yaml "$@"

