- name: "Cleanup"
  tags:
    - never
    - cleanup
  file:
    dest: "{{ item }}"
    state: absent
  loop:
    - "~/.cache/nvim"
    - "~/.config/nvim"
    - "~/.config/todo"
    - "~/.config/todo/config"
    - "~/.config/todofish.conf"
    - "~/.ctags"
    - "~/.local/share/nvim"
    - "~/.todo.actions.d/"
    - "~/.vale.ini"
    - "~/.vim_undo"
