- import_tasks: cleanup.yaml

- name: "Install"
  tags:
    - nvim
    - vim
  block:

    - name: "Ensure config dir exists"
      file:
        dest: "{{ item }}"
        state: directory
      loop:
        - "~/.host/config/nvim"
        - "~/.config/nvim"

    - name: Install base packages
      kewlfft.aur.aur:
        name:
          - neovim
          - python-pynvim
          - tree-sitter
        use: yay
        update_cache: True
      become: yes
      become_user: aur_builder

    - name: "EnvVars"
      tags:
        - fish
      copy:
        content: |
          #set -gx EDITOR "vim";
          #set -gx VISUAL "vim";
          #set -gx GUI_EDITOR "vim";
          fish_add_path --path -a ~/.local/share/nvim/site/pack/packer/opt/vim-iced/bin
        dest: "~/.config/fish/conf.d/20_nvim-vars.fish"

    - name: "Command"
      copy:
        content: |
          #!/bin/bash
          exec -a "$0" "/usr/bin/nvim" "$@"
        dest: "~/.local/bin/{{ item }}"
        mode: 0755
      loop:
        - "vim"
        - "nvim"

    - template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: "neovim/ctags", dest: "~/.ctags" }
        - { src: "neovim/vale.ini", dest: "~/.vale.ini" }
        - { src: "neovim/init.lua", dest: "~/.config/nvim/init.lua" }
        - { src: "neovim/init.lua", dest: "~/.host/config/nvim/init.lua" }

- import_tasks: notes.yaml
