#!/usr/bin/env python

from builtins import super
from os import path
from datetime import datetime
from copy import copy, deepcopy

import todoist

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, GObject, GLib

CONFIG = path.expanduser("~/.config/todoist.api")


def find_diff(dict1, dict2):
    differences = []
    for key in dict1.keys(): 
        if type(dict1[key]) is dict:
            return find_diff(dict1[key], dict2[key])
        else:
            if not dict1[key] == dict2[key]:
                differences.append((key, dict1[key], dict2[key]))
    return differences


class Prompt(Gtk.Dialog):
    def __init__(self, message):
        super().__init__()
        self.set_decorated(False)
        self.box = self.get_content_area()
        self.set_default_size(450, 100)

        self.entry = Gtk.Entry()
        self.entry.set_text(message)
        self.entry.connect("destroy", Gtk.main_quit)
        self.box.pack_start(self.entry, True, True, 0)

        self.task_due = Gtk.Entry()
        self.task_due.connect("destroy", Gtk.main_quit)
        self.box.pack_start(self.task_due, True, True, 0)


class APITokenPrompt(Prompt):
    def __init__(self, reason=""):
        super().__init__("API Token")
        self.entry.connect("activate", self.save_api)

        label = Gtk.Label()
        if reason != "":
            reason += ". "

        label.set_markup(
            "{}<a href='https://todoist.com/prefs/integrations'>Get your API token here</a>".format(
                reason
            )
        )
        self.box.pack_start(label, True, True, 0)

    def save_api(self, *args):
        with open(CONFIG, "w") as stream:
            stream.write(self.entry.get_text())
        self.destroy()


class NewTaskWindow(Prompt):
    def __init__(self):
        super().__init__("")
        self.entry.connect("activate", self.create_task)

        self.label = Gtk.Label()
        self.box.pack_start(self.label, True, True, 0)

        with open(CONFIG) as stream:
            self.api = todoist.TodoistAPI(stream.read())

        self.id = None
        self.item = None

    def create_task(self, *args):
        task = self.entry.get_text()
        task_due = self.task_due.get_text()
        status = f"{datetime.now().strftime('%I:%M:%S %p')}: "

        if not self.id:
            res = self.api.quick.add(task)
            if res.get("error_tag") == "AUTH_INVALID_TOKEN":
                show_prompt(APITokenPrompt("Invalid token"))

            self.id = res.get('id')
            if self.id:
                self.task_due.connect("activate", self.create_task)
        else:
            item = self.api.items.get_by_id(self.id)
            if task_due:
                task_due = {'string': task_due}
            else:
                task_due = None
            item.update(content=task, due=task_due)

            try:
                res = self.api.commit()
                if (self.item["content"] == item["content"]) and (self.item["due"] == item["due"]):
                    Gtk.main_quit()
            except todoist.api.SyncError:
                status = f"{status} Error!"

        self.item = deepcopy(self.api.items.get_by_id(self.id))

        self.entry.set_text(self.item["content"])
        if (due := self.item['due']):
            if (due_date := due['string']):
                self.task_due.set_text(due_date)
            if 'date' in due:
                status = f"{status}Due: {due['date']}, Rec:{due['is_recurring']}"

        self.label.set_text(status)

    def exit(self, *args):
        self.destroy()


def show_prompt(prompt):
    prompt.show_all()
    Gtk.main()


def main():
    if not path.exists(CONFIG):
        show_prompt(APITokenPrompt("Missing token"))
    show_prompt(NewTaskWindow())


if __name__ == "__main__":
    main()
