- name: "reload services"
  become: True
  systemd:
    name: "{{ item }}"
    enabled: False
    daemon_reload: True
  loop:
      - "restic-backup.timer"
      - "restic-backup.service"

- name: "reload services"
  become: True
  systemd:
    name: "{{ item }}"
    enabled: True
    daemon_reload: True
  loop:
      - "restic-backup.timer"
      - "restic-backup.service"
