- import_tasks: cleanup.yaml

- name: "Install"
  tags:
    - fonts
  block:

    - name: "Install FiraMono"
      kewlfft.aur.aur:
        name:
          - otf-nerd-fonts-fira-mono
          - ttf-ancient-fonts
          - noto-fonts-emoji
        use: yay
      become: yes
      become_user: aur_builder
