---
- name: "Install"
  ansible.builtin.include_tasks: "install.yaml"

- name: "Create dirs"
  ansible.builtin.file:
    dest: "{{ item.dir }}"
    state: directory
    mode: "0755"
  loop:
    - {dir: "~/.cache"}

- name: "Download FiraCode"
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/FiraCode.zip"
    dest: "~/.cache/FiraCode.zip"
    mode: "0644"

- name: "Download FiraMono"
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/FiraMono.zip"
    dest: "~/.cache/FiraMono.zip"
    mode: "0644"

- name: "Ensure .fonts exists"
  ansible.builtin.file:
    dest: "~/.fonts"
    state: directory
    mode: "0755"

- name: "Unpack fonts"
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: "~/.fonts"
    remote_src: true
    mode: "0755"
  loop:
    - "~/.cache/FiraMono.zip"
    - "~/.cache/FiraCode.zip"

- name: "If Void"
  when: ansible_os_family == "Void"
  block:

    - name: Disable bitmap fonts
      ansible.builtin.file:
        src: "/usr/share/fontconfig/conf.avail/70-no-bitmaps.conf"
        dest: "/etc/fonts/conf.d/70-no-bitmaps.conf"
        state: link
      become: true
